### ISSUE TITLE
Update 1.17.1 breaks ps extension

### ISSUE THREAD

**Issue by v2kiran** [PowerShell/vscode-powershell#1054]
### System Details

- Operating system name and version:windows 10
- VS Code version: 1.17.1
- PowerShell extension version:
- Output from `$PSVersionTable`:5.1

### Issue Description

the update 1.17.1 released a couple of days ago seems to have broken the ps extension. the status bar at the bottom right hand corner says "starting powershell" . The console just displays the header "powershell integrated console" and no prompt. killing the terminal dosent help.

![image](https://user-images.githubusercontent.com/7691373/31514051-af8b01ae-af90-11e7-858b-83bee2c5ff87.png)

**Comment by GHRoss** [comment]
Yep. I get this too.

**Comment by xayangjing** [comment]
yep, I get this too.
No out put when I run powershell with code runner .
the code always reported
[Running] powershell -ExecutionPolicy ByPass -File "d:\Powercli-scripts\Temp\Untitled2.ps1"

[Done] exited with code=-4058 in 0.002 seconds
vscode version:1.17.0 and 1.17.1
code-runner 0.7.3

<a href="https://ibb.co/gc0pmR"><img src="https://preview.ibb.co/cP6jLm/2017_10_17_13_16_39_1_ps1_Temp_Visual_Studio_Code.png" alt="2017_10_17_13_16_39_1_ps1_Temp_Visual_Studio_Code" border="0"></a>

[<a href="https://imgbb.com/"><img src="https://image.ibb.co/fJLWi6/2017_10_17_13_40_29_testing_py_Powercli_scripts_Visual_Studio_Code.png" alt="2017_10_17_13_40_29_testing_py_Powercli_scripts_Visual_Studio_Code" border="0"></a>](url)

**Comment by dsolodow** [comment]
This might be resolved by Code 1.17.2

**Comment by GHRoss** [comment]
I can confirm that this is fixed in 1.17.2 running 1703.

Terminal is s l o w to start though.

**Comment by dingliu** [comment]
Unfortunately, it still exists on my PC:

* Windows 7 Professional SP1 
* VS code 1.17.2 x64 
* PowerShell Extension 1.4.3

**Comment by daviwil** [comment]
For those of you still seeing this issue, could you please capture logs and post them here?

Instructions: https://github.com/PowerShell/vscode-powershell#2-capture-verbose-logs-and-send-them-to-us

**Comment by dingliu** [comment]
@daviwil No problem:
[vscode-ext-powershell-logs.zip](https://github.com/PowerShell/vscode-powershell/files/1415724/vscode-ext-powershell-logs.zip)

Thank you very much for your help. :smiley:

**Comment by hematic** [comment]
![image](https://user-images.githubusercontent.com/7807586/32020160-47e83ca8-b99d-11e7-990f-88e7e609e51f.png)

This is the error i have been getting since the update

**Comment by daviwil** [comment]
@dingliu can you turn on Verbose logging so that I can see mroe output from your logs?  Add this to your settings, restart VS Code, then try starting the PowerShell extension again:

```
  "powershell.developer.editorServicesLogLevel": "Verbose"
```

**Comment by daviwil** [comment]
@hematic are you running VS Code as Administrator or under normal privileges?

**Comment by hematic** [comment]
@daviwil Normal user, same as i do every day.

**Comment by dingliu** [comment]
@daviwil Sure, I'm sending the logs I collected today. :smiley: 

[vscode-powershell-ext-logs-20171026.zip](https://github.com/PowerShell/vscode-powershell/files/1418405/vscode-powershell-ext-logs-20171026.zip)

Also, I double checked my settings before collecting logs.
![vs code setting](https://user-images.githubusercontent.com/888873/32054288-f3f4f2be-ba2b-11e7-8130-a1aaab634cd4.png)
![vs code problem](https://user-images.githubusercontent.com/888873/32054304-ff28bbe8-ba2b-11e7-8c96-a95b44538960.png)
![vs code powershell extension version](https://user-images.githubusercontent.com/888873/32054305-03848c62-ba2c-11e7-802c-beb4dbbcd2e0.png)
![vs code version](https://user-images.githubusercontent.com/888873/32054309-0663eefa-ba2c-11e7-82c2-811b2b272b93.png)

Thanks again.

**Comment by daviwil** [comment]
Thanks for the detailed info!  This is very strange, seems that everything starts up fine despite the fact that it doesn't finish loading for you.  Do you eventually see an error message appear from the PowerShell extension?  Do you get the correct IntelliSense behavior in the editor?

**Comment by dingliu** [comment]
@daviwil Thank you so much for the prompt response.

As I experimented just now. I didn't see any error message, even after I have VS Code left open for about 8 or 9 minutes. Besides that, the IntelliSense is working for snippets, but not for Cmdlets. Following is my log file and screenshots.
[vscode-powershell-ext-logs-20171026-1.zip](https://github.com/PowerShell/vscode-powershell/files/1420045/vscode-powershell-ext-logs-20171026-1.zip)

![1](https://user-images.githubusercontent.com/888873/32076860-61a75160-ba6f-11e7-8850-499a672146dc.png)
![2](https://user-images.githubusercontent.com/888873/32076861-63b9d734-ba6f-11e7-8473-a7e9a5184d83.png)
![3](https://user-images.githubusercontent.com/888873/32076865-6563408e-ba6f-11e7-8624-df43c5051300.png)

**Comment by rkeithhill** [comment]
The reason you are not getting cmdlet completion is that PowerShell hasn't fully started.  Until that "Starting PowerShell..." message goes away and is replaced by the PS version, very few of the PowerShell extension's features will be available.

**Comment by daviwil** [comment]
Yeah, the problem is that the language server never fully starts up, it just hangs on Starting PowerShell.

@dingliu what other extensions do you have installed in VS Code?  I notice that there's a message about Application Insights in the status bar.  Can you try disabling all other extensions except for the PowerShell extension and restart VS Code?  Another extension may be interfering with the PowerShell extension, I've seen this once before.

**Comment by dingliu** [comment]
@daviwil Yes, you're exactly right. After I disabled other extensions, the PowerShell Integrated Console starts smoothly now. I'm checking which extension caused this problem.

**Comment by dingliu** [comment]
@daviwil The PowerShell Integrated Console can't start up if _Azure Application Insights_ extension is enabled. Perhaps it is because of that the Azure Application Insights extension has not been setup for initial use yet.

**Comment by daviwil** [comment]
Thanks for pinpointing the right extension!  I'll see if I can figure out why that extension causes a conflict.

**Comment by dingliu** [comment]
You are very welcome. Thank you and all other maintainers for this fantastic extension! :smiley:

**Comment by daviwil** [comment]
Strangely I can't seem to reproduce the hang with the issue.  Do you see any errors in the Developer Tools in VS Code?  When the PS extension hangs, click the menu "Help -> Toggle Developer Tools" and when the tools pane pops up, click the red X icon at the top right if you see one:

![image](https://user-images.githubusercontent.com/79405/32109346-581c3f64-bae9-11e7-9b7f-902fd496be54.png)

Copy the contents of that console and paste them here.  Thanks!

**Comment by dingliu** [comment]
```
console.ts:123 [Extension Host] vscode-icons is active!
console.ts:123 [Extension Host] context set
console.ts:123 [Extension Host] new channel
console.ts:123 [Extension Host] rejected promise not handled within 1 second
t.log @ console.ts:123
shell.ts:454 [msazurermtools.azurerm-vscode-tools] Cannot read property 'indexOf' of null: TypeError: Cannot read property 'indexOf' of null
	at Function.AppInsightsAsyncCorrelatedErrorWrapper.orig.prepareStackTrace (C:\Users\dliu\.vscode\extensions\msazurermtools.azurerm-vscode-tools-0.3.7\node_modules\applicationinsights\out\AutoCollection\CorrelationContextManager.js:155:47)
	at Function.NativeError.prepareStackTrace (C:\Users\dliu\.vscode\extensions\msazurermtools.azurerm-vscode-tools-0.3.7\node_modules\zone.js\dist\zone-node.js:900:30)
	at consoleError (C:\Users\dliu\.vscode\extensions\msazurermtools.azurerm-vscode-tools-0.3.7\node_modules\zone.js\dist\zone-node.js:420:240)
	at _loop_1 (C:\Users\dliu\.vscode\extensions\msazurermtools.azurerm-vscode-tools-0.3.7\node_modules\zone.js\dist\zone-node.js:449:25)
	at drainMicroTaskQueue (C:\Users\dliu\.vscode\extensions\msazurermtools.azurerm-vscode-tools-0.3.7\node_modules\zone.js\dist\zone-node.js:453:21)
	at <anonymous>
e.onUnexpectedError @ shell.ts:454
```

![1](https://user-images.githubusercontent.com/888873/32109834-d8ee7246-bb03-11e7-80ee-b83206868a2c.png)

**Comment by tehsuk** [comment]
I was running into the same issue & found the perforce plugin was causing the hang.   https://github.com/stef-levesque/vscode-perforce/issues/105

**Comment by stef-levesque** [comment]
I couldn't repro with the perforce extension, neither on 1.17.2 nor 1.18.0-insider. 
Any luck with more detailed repro steps ?

**Comment by SydneyhSmith** [comment]
Closing as inactive/resolved will re-open if this issue is still occurring. Thanks!
