### ISSUE TITLE
New-EditorFile triggers an error messsage

### ISSUE THREAD

**Issue by alexandair** [PowerShell/vscode-powershell#1210]
```
PS C:\projects\TestPipeline> code -v
1.20.1
f88bbf9137d24d36d968ea6b2911786bfe103002
x64
PS C:\projects\TestPipeline> $pseditor.EditorServicesVersion

Major  Minor  Build  Revision
-----  -----  -----  --------
1      6      0      0


PS C:\projects\TestPipeline> code --list-extensions --show-versions
mauve.terraform@0.0.20
mindginative.terraform-snippets@2.0.1
ms-azuretools.vscode-azurestorage@0.2.0
ms-kubernetes-tools.vscode-kubernetes-tools@0.1.5
ms-vscode.azure-account@0.3.1
ms-vscode.azurecli@0.4.0
ms-vscode.PowerShell@1.6.0
ms-vsts.team@1.122.0
msazurermtools.azurerm-vscode-tools@0.4.0
octref.vscode-json-transform@0.1.2
pnp.polacode@0.2.2
vscoss.vscode-ansible@0.1.3
PS C:\projects\TestPipeline> $PSVersionTable

Name                           Value
----                           -----
PSVersion                      5.1.16299.98
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.16299.98
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
```

### Issue Description

When I run New-EditorFile, a new file is created, but I also get an error message:
```
PS C:\projects\TestPipeline> New-EditorFile
Exception calling "GetEditorContext" with "0" argument(s): "One or more errors occurred."
At C:\Users\aleksandar\.vscode\extensions\ms-vscode.powershell-1.6.0\modules\PowerShellEditorServices\Commands\P
ublic\CmdletInterface.ps1:152 char:13
+             $psEditor.GetEditorContext().CurrentFile.InsertText(($val ...
+             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [], MethodInvocationException
    + FullyQualifiedErrorId : AggregateException
```

### Attached Logs

Follow the instructions in the [README](https://github.com/PowerShell/vscode-powershell#reporting-problems)
about capturing and sending logs.

**Comment by tylerl0706** [comment]
Interesting. Does that error happen when you run:

```
$psEditor.GetEditorContext()
```

In the integrated console?

**Comment by Benny1007** [comment]
Does for me

:\MICROSOFT\PowerShell> $psEditor.GetEditorContext()
Exception calling "GetEditorContext" with "0" argument(s): "One or more errors occurred."
At line:1 char:1
+ $psEditor.GetEditorContext()
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [], MethodInvocationException
    + FullyQualifiedErrorId : AggregateException

I:\MICROSOFT\PowerShell> New-EditorFile
Exception calling "GetEditorContext" with "0" argument(s): "One or more errors occurred."
At C:\Users\bensh\.vscode\extensions\ms-vscode.powershell-1.6.0\modules\PowerShellEditorServices\Commands\Public\CmdletInterface.ps1:152 char:13
+             $psEditor.GetEditorContext().CurrentFile.InsertText(($val ...
+             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [], MethodInvocationException
    + FullyQualifiedErrorId : AggregateException

**Comment by SeeminglyScience** [comment]
I can repro if I comment out `"files.defaultLanguage": "powershell"` from my settings.

@tylerl0706 there's an overload on `openTextDocument` that allows you to specify what language the new text document should be.  If we just always set that to `powershell` it should resolve the issue.

**Comment by tylerl0706** [comment]
Perfect for the hackathon!

**Comment by tylerl0706** [comment]
Thanks for the report everyone!

**Comment by alexandair** [comment]
`$psEditor.GetEditorContext()` works on my machine without a problem. New-EditorFile still fails.

**Comment by tylerl0706** [comment]
This only seems to happen with Untitled files... because:

```
Get-Process | New-EditorFile -Path foo.txt
```

works fine.

**Comment by Benny1007** [comment]
I can't reproduce this with the latest version of the extension.

**Comment by TylerLeonhardt** [comment]
Ah yes this was fixed in #1580. We can close this. Thanks!
