### ISSUE TITLE
Extra Intellisense coming back for argument completers

### ISSUE THREAD

**Issue by pcgeek86** [PowerShell/vscode-powershell#162]
I'm getting back snippets, and other auto-completion results, along with my custom auto-completion results. I think we should only be returning custom auto-completion results, and not generic items that aren't relevant to the current context.

![image](https://cloud.githubusercontent.com/assets/466713/14897255/88c403a4-0d3e-11e6-84a7-383fc260f42c.png)

Happening on VS Code Insiders and release versions.

Cheers,
**Trevor Sullivan**
https://trevorsullivan.net
https://twitter.com/pcgeek86

**Comment by daviwil** [comment]
Thanks!  This could be related to how we're doing IntelliSense a little differently than other languages.  I'll have to look into it, but it might be something we can ask VS Code team to help with.

**Comment by pcgeek86** [comment]
Related to this, parameters that are typed as an enumeration are also including snippets in the Intellisense results. Instead, we should limit the results to the enumeration values.

<img width="694" alt="screen shot 2017-05-18 at 11 35 12 am" src="https://cloud.githubusercontent.com/assets/466713/26221233/a0e0f396-3bca-11e7-8006-fb073fa7f678.png">

**Comment by rkeithhill** [comment]
@pcgeek86 What completions do you get from PowerShell console / PSReadline for this parameter?

**Comment by pcgeek86** [comment]
![new-eccachecluster](https://cloud.githubusercontent.com/assets/466713/26412230/e21450c4-405c-11e7-8702-c81660a01ccb.gif)

@rkeithhill

**Comment by daviwil** [comment]
Seems that we're giving snippet completions in some places where they aren't needed.  I'll check to see if there's a way to contextually suppress snippet completion items.

**Comment by rkeithhill** [comment]
This broke somewhere between 0.12.2:
![image](https://cloud.githubusercontent.com/assets/5177512/26415404/9dc8469c-406f-11e7-8947-3535e9c47433.png)

and 1.1.0:

![image](https://cloud.githubusercontent.com/assets/5177512/26415456/c978dc84-406f-11e7-9017-348dfe561162.png)

**Comment by pcgeek86** [comment]
@rkeithhill Isn't that kind of comparing apples and oranges though? Parameter name vs. parameter value.

**Comment by rkeithhill** [comment]
Yes.  Sorry hands typing `-` by themselves. Not what I meant to do.  :-)  Still, same result for 0.12.2 (other than icon):

![image](https://cloud.githubusercontent.com/assets/5177512/26415613/5e9ef7a8-4070-11e7-969a-98363c81665a.png)

Note: no scroll bar or extra completion items.

**Comment by daviwil** [comment]
It is likely that something did break between 0.12.2 and 1.0.0, we changed the version of the language server client in the PowerShell extension and upgraded to the new LSP version in PSES.  I bet we forgot to wire something up.  Thanks for figuring that out Keith, I'll see if I can find tthe mismatch.

**Comment by rkeithhill** [comment]
I think something might have changed WRT completion list sorting in VSCode particularly when there is no text to the left of where list appears.  In the case above there's a space (not a `.` or `-` or `::`).   See https://github.com/Microsoft/vscode/issues/26096#issuecomment-299833097

**Comment by pcgeek86** [comment]
@tylerl0706 I'm not sure what level of effort is required to resolve this, but a fix for this issue would help clean up the VSCode-PowerShell experience.

**Comment by Kitsune-Fox** [comment]
I'm finding this to be a huge issue for me as well.

There are a few things that it does really stupidly.
I apologise if this isn't the right place for it but this issue is part of the intellisense issues I'm seeing.

When for instance using dot notation, it should default to the properties of the object and not to the last used method. This causes me a lot of pain, I'll end up having to scroll up to get to the properties because I use the properties way more often than the methods.

I cant upload screenshots unfortunately but I see the following behavior:
[string]$Var1 = 'Text'

ISE:
$Var.{This will open the intellisense list at the first property of the object}

VSC:
$Var.{This will default to the last used method, which may have been hours ago}

**Comment by JustinGrote** [comment]
@TylerLeonhardt I can't reproduce this one on either 5.1 or 7



I can't reproduce any situation where the only thing I don't get is the expected content and snippets, and snippets can be hidden with the `editor.snippetsuggestings` setting, or (my preference), changed to "bottom"

It also works with ArgumentCompleters fine, though there is a bit of problem if a command has multiple parametersets. For instance, given the first argumentcompleter example:
https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.core/register-argumentcompleter?view=powershell-7

It only works if you "intellisense select" the `Id` parameter, just typing it won't work:
![Capture](https://user-images.githubusercontent.com/15258962/79585483-b80b2d00-8084-11ea-9ec2-05397178a08d.gif)



Environment Information
=====

Visual Studio Code
-----

| Name | Version |
| --- | --- |
| Operating System | Windows_NT x64 10.0.19041 |
| VSCode | 1.45.0-insider|
| PowerShell Extension Version | 2020.4.2 |

PowerShell Information
-----

|Name|Value|
|---|---|
|PSVersion|7.0.0|
|PSEdition|Core|
|GitCommitId|7.0.0|
|OS|Microsoft Windows 10.0.19041|
|Platform|Win32NT|
|PSCompatibleVersions|1.0 2.0 3.0 4.0 5.0 5.1.10032.0 6.0.0 6.1.0 6.2.0 7.0.0|
|PSRemotingProtocolVersion|2.3|
|SerializationVersion|1.1.0.1|
|WSManStackVersion|3.0|

**Comment by rkeithhill** [comment]
I believe the original issue is what you see when parameter name/value completion is not working at all.  I'd say this one is fixed.

**Comment by JustinGrote** [comment]
@rkeithhill does it make sense to break out two new issues then if they don't already exist?

1. Inconsistent Intellisense if a command has multiple parametersets
2. [Feature Request] https://github.com/PowerShell/vscode-powershell/issues/162#issuecomment-515939246 - Add setting preference to disable intellisense "most recent history" suggestion for dot-sourced properties

**Comment by pcgeek86** [comment]
> I believe the original issue is what you see when parameter name/value completion is not working at all. I'd say this one is fixed.

Actually, you'll notice in the original issue report, that I have a custom argument completer / Intellisense handler. Still, the VSCode snippets are being returned alongside my Intellisense results, which is undesirable. I'm still seeing this behavior in PowerShell 7.0 with VSCode on Windows 10.

![image](https://user-images.githubusercontent.com/466713/79594036-3241ae80-8091-11ea-9043-0288fda0f928.png)

**Comment by JustinGrote** [comment]
@pcgeek86 Did you see my comment about turning off the snippets?
This vscode setting: `editor.snippetsuggestings`

**Comment by pcgeek86** [comment]
@JustinGrote Thanks, I missed that. I don't want to disable snippets though. I want snippets to show up when I'm not using argument completers, and when I am using argument completers, I don't want snippets to show up and pollute the results.

**Comment by JustinGrote** [comment]
@pcgeek86 understood, this comes from VSCode and not the powershell extension so I don't know if there's a way to do an "if" filter.

I just set my snippetsuggestions to "bottom" and they are always at the bottom even if I select them so they don't get mixed in, is that sufficient? The icon makes it very clear the snippets are separate.

I agree it's a "nice to have" for it to be contextual and it's also subjective, for instance another person might *want* snippets at the parameter level, say for a snippet that has a parenthesis evaluation of a parameter.

**Comment by SydneyhSmith** [comment]
Thanks everyone for the continued interest on this issue and discussion here. Because of the way snippets are provided in VSCode they are not context-aware so unfortunately there isnt anything we can do for this issue from the PowerShell extension side so I am going mark this issue as Resolution-External. The best you can do is make this configuration language specific using the setting Justin provided  i.e.
 ```
"[powershell]":{
    "editor.snippetSuggestions": "bottom" //or "none"
}
```
