### ISSUE TITLE
PowerShell extension (and Integrated Console) never starts

### ISSUE THREAD

**Issue by dtbiedrzycki** [PowerShell/vscode-powershell#1673]
### System Details

System Details Output
```
### VSCode version: 1.30.1 dea8705087adb1b5e5ae1d9123278e178656186a x64

### VSCode extensions:
christian-kohler.npm-intellisense@1.3.0
christian-kohler.path-intellisense@1.4.2
CoenraadS.bracket-pair-colorizer@1.0.61
DavidAnson.vscode-markdownlint@0.22.0
dbaeumer.vscode-eslint@1.7.2
eg2.vscode-npm-script@0.3.5
jasonnutter.search-node-modules@1.3.0
jebbs.plantuml@2.10.1
ms-mssql.mssql@1.4.0
ms-vscode.csharp@1.17.1
ms-vscode.PowerShell@1.10.2
rebornix.ruby@0.21.0
waderyan.nodejs-extension-pack@0.1.9
xabikos.JavaScriptSnippets@1.7.2
yzhang.markdown-all-in-one@1.8.0


### PSES version:

### PowerShell version:

Name                           Value
----                           -----
PSVersion                      5.1.16299.666
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.16299.666
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
```

### Issue Description

All right click console options fail (i.e. Run Selection).

#### Expected Behaviour

If I highlight code and press F8 (or right click and Run Selection), I expect the command(s) to be run in the terminal window.

#### Actual Behaviour

A pop-up appears stating `<ConsoleFeature>: Unable to instantiate; language client undefined.`

### Attached Logs

There are _no_ logs in the extension logs folder (even with logs set to Diagnostic) and the lines below are the only output in the PowerShell Extension console:
```
12/26/2018 10:34:57 AM [NORMAL] - Visual Studio Code v1.30.1 64-bit
12/26/2018 10:34:57 AM [NORMAL] - PowerShell Extension v1.10.2
12/26/2018 10:34:57 AM [NORMAL] - Operating System: Windows 64-bit
12/26/2018 10:35:10 AM [ERROR] - <ConsoleFeature>: Unable to instantiate; language client undefined.
```

**Comment by TylerLeonhardt** [comment]
Can you confirm that the PowerShell Integrated Console is open?

**Comment by dtbiedrzycki** [comment]
I don't believe it is. When I try to open it via the command palette, nothing happens either.

**Comment by SydneyhSmith** [comment]
@dtbiedrzycki  it would be helpful to know what command you were trying to run when you reached this error, a screenshot of your VSCode environment when this occurred would be even better, thanks!

**Comment by SydneyhSmith** [comment]
@dtbiedrzycki this should be fixed by a recent PR in #1690

**Comment by Tulkis** [comment]
Here an approaching issue:
`1/16/2019 5:38:54 PM [ERROR] - The language service could not be started: 
1/16/2019 5:38:54 PM [ERROR] - Timed out waiting for session file to appear.
1/16/2019 5:39:33 PM [ERROR] - <ConsoleFeature>: Unable to instantiate; language client undefined.`

**Comment by Tulkis** [comment]
> 
> 
> Here an approaching issue trying to open new Terminal after default crashes:
> `1/16/2019 5:38:54 PM [ERROR] - The language service could not be started: 1/16/2019 5:38:54 PM [ERROR] - Timed out waiting for session file to appear. 1/16/2019 5:39:33 PM [ERROR] - <ConsoleFeature>: Unable to instantiate; language client undefined.`

Ok, I solved this changing the loglevel on VSCode settings from Warning to Normal. Maybe a Powershell modules update broke it?
Thanks

**Comment by SydneyhSmith** [comment]
@dtbiedrzycki Closing as the update to the extension that should fix this is out, will re-open if this issue is still happening!

**Comment by dtbiedrzycki** [comment]
Hey @SydneyhSmith, I've updated the PowerShell extension to version 1.11.0 and my problem remains. See the attached gif showing the issue:
![1673-error](https://user-images.githubusercontent.com/707842/51746202-90a5fa00-20a5-11e9-80e5-c000efe08fbb.gif)

**Comment by IzzyRise** [comment]
I had this exactly same issue. Disabling, enabling then reload solved it for me.

**Comment by SydneyhSmith** [comment]
Thanks for reporting this, it could be from being on a restricted system, is your environment restricted in any way (group policy etc.), if so this could be the cause--try this https://docs.microsoft.com/en-us/powershell/scripting/components/vscode/using-vscode?view=powershell-6#installing-the-powershell-extension-on-restricted-systems and let us know if that helps at all.

**Comment by dtbiedrzycki** [comment]
> I had this exactly same issue. Disabling, enabling then reload solved it for me.

This did not work for me :(.

**Comment by dtbiedrzycki** [comment]
> Thanks for reporting this, it could be from being on a restricted system, is your environment restricted in any way (group policy etc.), if so this could be the cause--try this https://docs.microsoft.com/en-us/powershell/scripting/components/vscode/using-vscode?view=powershell-6#installing-the-powershell-extension-on-restricted-systems and let us know if that helps at all.

I ran the command provided in the link, was not prompted, and the command executed successfully. I also tried running VS Code as an administrator and still get the same behavior.

**Comment by dtbiedrzycki** [comment]
I've also tried uninstalling and re-installing VS Code and get the same result as well.

**Comment by SydneyhSmith** [comment]
@dtbiedrzycki we are trying to diagnose this issue, would you mind looking in the logs file, they should be at `~/.VSCode/extensions/ms-vscode.powershell-1.11.0/logs` ? Thanks!

**Comment by dtbiedrzycki** [comment]
The directory is empty :(
I also double checked and I have the "powershell.developer.editorServicesLogLevel" set to "Diagnostic".

**Comment by chrisalimiller** [comment]
We're having the same issue running any commands through powershell terminal. This was working fine for a few days and now nothing. Are there any updates on this issue?

**Comment by tkre** [comment]
For me the problem appeared literally over lunch yesterday. Everything was working in the morning, not so in the afternoon. My machine did not do Windows updates yesterday, I did not install or remove any software, no group policies whatsoever, execution policy is set zu unrestricted systemwide.

My setup:

`Version: 1.32.3 (user setup)
Commit: a3db5be9b5c6ba46bb7555ec5d60178ecc2eaae4
Date: 2019-03-14T23:43:35.476Z
Electron: 3.1.6
Chrome: 66.0.3359.181
Node.js: 10.2.0
V8: 6.6.346.32
OS: Windows_NT x64 10.0.17763`

`Name: PowerShell
Id: ms-vscode.powershell
Description: Develop PowerShell scripts in Visual Studio Code!
Version: 1.12.0
Publisher: Microsoft
VS Marketplace Link: https://marketplace.visualstudio.com/items?itemName=ms-vscode.PowerShell`

`PS C:\Users\TK> $PSVersionTable

Name                           Value                                                                                                                                     
----                           -----                                                                                                                                     
PSVersion                      5.1.17763.316                                                                                                                             
PSEdition                      Desktop                                                                                                                                   
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}                                                                                                                   
BuildVersion                   10.0.17763.316                                                                                                                            
CLRVersion                     4.0.30319.42000                                                                                                                           
WSManStackVersion              3.0                                                                                                                                       
PSRemotingProtocolVersion      2.3                                                                                                                                       
SerializationVersion           1.1.0.1    `

When I open any .ps1 file in editor, the lower right corner of vs code displays "Starting Powershell". It stays like this for about a Minute (did not measure it) then a notification informs me, that it could not be startet and the text changes to "Initialization Error". 

I set the log level to diagnostic but information remains a bit sparse.
vscode-powershell.log
`2019-4-2 07:49:48 [NORMAL] - Language server starting --
2019-4-2 07:49:48 [NORMAL] -     exe: C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe
2019-4-2 07:49:48 [NORMAL] - Path specified by 'powerShellExePath' setting - '' - not found, reverting to default PowerShell path.
2019-4-2 07:49:48 [NORMAL] -     args: c:\Users\TK\.vscode\extensions\ms-vscode.powershell-1.12.0\modules\PowerShellEditorServices\Start-EditorServices.ps1 -HostName 'Visual Studio Code Host' -HostProfileId 'Microsoft.VSCode' -HostVersion '1.12.0' -AdditionalModules @('PowerShellEditorServices.VSCode') -BundledModulesPath 'c:\Users\TK\.vscode\extensions\ms-vscode.powershell-1.12.0\modules' -EnableConsoleRepl -LogLevel 'Diagnostic' -LogPath 'c:\Users\TK\.vscode\extensions\ms-vscode.powershell-1.12.0\logs\1554184188-29843e1a-63c5-4aee-ae2c-77e45359917a1554156943801\EditorServices.log' -SessionDetailsPath 'c:\Users\TK\.vscode\extensions\ms-vscode.powershell-1.12.0\sessions\PSES-VSCode-9712-407966' -FeatureFlags @()
2019-4-2 07:49:48 [NORMAL] - powershell.exe started, pid: 9036
2019-4-2 07:49:50 [NORMAL] - powershell.exe terminated or terminal UI was closed
2019-4-2 07:51:48 [NORMAL] - Language server startup failed.
2019-4-2 07:51:48 [ERROR] - The language service could not be started: 
2019-4-2 07:51:48 [ERROR] - Timed out waiting for session file to appear.
`

Start-EditorServices-EditorServices.log:
`**********************
nStart der Windows PowerShell-Aufzeichnung
Startzeit: 20190402074948
Benutzername: NB-MUM-TK\TK
RunAs-Benutzer: NB-MUM-TK\TK
Konfigurationsname: 
Computer: NB-MUM-TK (Microsoft Windows NT 10.0.17763.0)
Hostanwendung: C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe -NoProfile -NonInteractive -ExecutionPolicy Bypass -EncodedCommand JgAgACcAYwA6AFwAVQBzAGUAcgBzAFwAVABLAFwALgB2AHMAYwBvAGQAZQBcAGUAeAB0AGUAbgBzAGkAbwBuAHMAXABtAHMALQB2AHMAYwBvAGQAZQAuAHAAbwB3AGUAcgBzAGgAZQBsAGwALQAxAC4AMQAyAC4AMABcAG0AbwBkAHUAbABlAHMAXABQAG8AdwBlAHIAUwBoAGUAbABsAEUAZABpAHQAbwByAFMAZQByAHYAaQBjAGUAcwBcAFMAdABhAHIAdAAtAEUAZABpAHQAbwByAFMAZQByAHYAaQBjAGUAcwAuAHAAcwAxACcAIAAtAEgAbwBzAHQATgBhAG0AZQAgACcAVgBpAHMAdQBhAGwAIABTAHQAdQBkAGkAbwAgAEMAbwBkAGUAIABIAG8AcwB0ACcAIAAtAEgAbwBzAHQAUAByAG8AZgBpAGwAZQBJAGQAIAAnAE0AaQBjAHIAbwBzAG8AZgB0AC4AVgBTAEMAbwBkAGUAJwAgAC0ASABvAHMAdABWAGUAcgBzAGkAbwBuACAAJwAxAC4AMQAyAC4AMAAnACAALQBBAGQAZABpAHQAaQBvAG4AYQBsAE0AbwBkAHUAbABlAHMAIABAACgAJwBQAG8AdwBlAHIAUwBoAGUAbABsAEUAZABpAHQAbwByAFMAZQByAHYAaQBjAGUAcwAuAFYAUwBDAG8AZABlACcAKQAgAC0AQgB1AG4AZABsAGUAZABNAG8AZAB1AGwAZQBzAFAAYQB0AGgAIAAnAGMAOgBcAFUAcwBlAHIAcwBcAFQASwBcAC4AdgBzAGMAbwBkAGUAXABlAHgAdABlAG4AcwBpAG8AbgBzAFwAbQBzAC0AdgBzAGMAbwBkAGUALgBwAG8AdwBlAHIAcwBoAGUAbABsAC0AMQAuADEAMgAuADAAXABtAG8AZAB1AGwAZQBzACcAIAAtAEUAbgBhAGIAbABlAEMAbwBuAHMAbwBsAGUAUgBlAHAAbAAgAC0ATABvAGcATABlAHYAZQBsACAAJwBEAGkAYQBnAG4AbwBzAHQAaQBjACcAIAAtAEwAbwBnAFAAYQB0AGgAIAAnAGMAOgBcAFUAcwBlAHIAcwBcAFQASwBcAC4AdgBzAGMAbwBkAGUAXABlAHgAdABlAG4AcwBpAG8AbgBzAFwAbQBzAC0AdgBzAGMAbwBkAGUALgBwAG8AdwBlAHIAcwBoAGUAbABsAC0AMQAuADEAMgAuADAAXABsAG8AZwBzAFwAMQA1ADUANAAxADgANAAxADgAOAAtADIAOQA4ADQAMwBlADEAYQAtADYAMwBjADUALQA0AGEAZQBlAC0AYQBlADIAYwAtADcANwBlADQANQAzADUAOQA5ADEANwBhADEANQA1ADQAMQA1ADYAOQA0ADMAOAAwADEAXABFAGQAaQB0AG8AcgBTAGUAcgB2AGkAYwBlAHMALgBsAG8AZwAnACAALQBTAGUAcwBzAGkAbwBuAEQAZQB0AGEAaQBsAHMAUABhAHQAaAAgACcAYwA6AFwAVQBzAGUAcgBzAFwAVABLAFwALgB2AHMAYwBvAGQAZQBcAGUAeAB0AGUAbgBzAGkAbwBuAHMAXABtAHMALQB2AHMAYwBvAGQAZQAuAHAAbwB3AGUAcgBzAGgAZQBsAGwALQAxAC4AMQAyAC4AMABcAHMAZQBzAHMAaQBvAG4AcwBcAFAAUwBFAFMALQBWAFMAQwBvAGQAZQAtADkANwAxADIALQA0ADAANwA5ADYANgAnACAALQBGAGUAYQB0AHUAcgBlAEYAbABhAGcAcwAgAEAAKAApAA==
Prozess-ID: 9036
PSVersion: 5.1.17763.316
PSEdition: Desktop
PSCompatibleVersions: 1.0, 2.0, 3.0, 4.0, 5.0, 5.1.17763.316
BuildVersion: 10.0.17763.316
CLRVersion: 4.0.30319.42000
WSManStackVersion: 3.0
PSRemotingProtocolVersion: 2.3
SerializationVersion: 1.1.0.1
**********************
`

I can run the Start-EditorServices.ps1 script with the same parameters as in the log file above manually, it outputs "Powershell Integrated Console" and stays like this. I don't know if that is the expected behavior but there is no error.

If I do install any older version of the PowerShell extension, it works as normal **once**. 

I can reproduce with an newly created Windows user account on my machine and a clean install of vs code and the extension. I cannot get my handy on another machine at the moment.

**Comment by SydneyhSmith** [comment]
If everyone could please update the extension and let us know if that solved your issues that would be really helpful!
@tkre your issue seems related to #1835

**Comment by illusive-man** [comment]
I have similar problem. On PS 6.1.0 it worked perfectly. After updating to 6.2.0 Switching from Windows Powershell session to PS Core 6 one, gives me Initialization Error message in status bar and some error info in Output. Check attached image.
![PS620_error](https://user-images.githubusercontent.com/25516639/57395009-a4e2b280-71cf-11e9-8b6c-226b25e63c46.png)

**Comment by rjmholt** [comment]
Exit code 2 seems to be file not found. Did this startup output [logs](https://github.com/PowerShell/vscode-powershell/blob/master/docs/troubleshooting.md#logs)?

Can you verify the location of your `pwsh` installation? Should be possible in a terminal with `where.exe pwsh`

**Comment by illusive-man** [comment]
Yep. 

Did nothing at all, just updated PS to 6.2.0. VS Сode itself and extension are always up to date. 
Here's location of pwsh.exe according to where.exe: C:\Program Files\PowerShell\6\pwsh.exe

**Comment by rjmholt** [comment]
Would you be able to set your log level to Diagnostic and upload any logs generated here (or send them through to the email address in the document)?

**Comment by illusive-man** [comment]
If you mean this one - "powershell.developer.editorServicesLogLevel": "Diagnostic" it was already enabled at the time I've posted the screenshot. So there's no additional info in logs I'm afraid.

When I switch from Windows Powershell (x64) to Powershell Core 6 (x64) I can't switch to terminal panel at all. It closes instantly. Switching back to Windows Powershell works fine. Terminal panel is accessible and shows common PS prompt. Reinstalled everything to no avail...

**Comment by rjmholt** [comment]
I assume you can run PS 6.2 in the console without error?

**Comment by rjmholt** [comment]
Also which PowerShell extension do you have installed? Can you report the output of `code --list-extensions`?

**Comment by rjmholt** [comment]
The first mystery is that if diagnostic logging is already enabled, I'd expect verbose output from PowerShell in the startup script.

Do you have verbose logs for the successful startup of the extension with PowerShell 5.1?

**Comment by illusive-man** [comment]
![2019-05-09_0-45-27](https://user-images.githubusercontent.com/25516639/57410673-1e8c9780-71f4-11e9-8ae9-d05d3977e314.png)

Yes. For 5.1 there's VERBOSE output in terminal. 
![2019-05-09_0-52-24](https://user-images.githubusercontent.com/25516639/57411053-24cf4380-71f5-11e9-9055-16c757064e6a.png)

Somehow I've got terminal panel in PS Core 6 session, and there is VERBOSE output for it (last paragraph). Don't pay attention to PS Prompt because it's unresponsive. Here's Output panel content for 6.2.0:
![2019-05-09_0-54-13](https://user-images.githubusercontent.com/25516639/57411169-737cdd80-71f5-11e9-9021-c63fc0789042.png)

**Comment by rjmholt** [comment]
Unfortunately this looks most like https://github.com/microsoft/vscode/issues/62953. VSCode is not good about sending through error messages, but there's some problem occurring when it tries to start the PowerShell process to run the extension on.

Maybe there's a permissions problem with the PS 6.2 executable?

**Comment by illusive-man** [comment]
Well, I logged in as a local administrator and all Administrators rights for pwsh.exe were there. I added Read & Execute (there was only Read) for my User\goujon user and restarted the PC. After that it VSC extension and terminal started to work fine. Not sure it was what I did lately, but definitely helped in my case. Thank you very much, @rjmholt!!! You're the saviour! :)
![2019-05-09_1-32-22](https://user-images.githubusercontent.com/25516639/57412732-6a423f80-71fa-11e9-85d7-be6e20f1ce36.png)

**Comment by rjmholt** [comment]
Great news! Glad I was able to help

**Comment by SydneyhSmith** [comment]
Assuming this is resolved for everyone since there has been no activity since my last check-in, please let us know if this is not the case, thanks!

**Comment by pgemme** [comment]
I was having this issue and reverting to 2019.5.0 fixed it for me.

**Comment by ActionExpress50** [comment]
> I was having this issue and reverting to 2019.5.0 fixed it for me.

+1. Need some fix.

**Comment by SydneyhSmith** [comment]
@ActionExpress50 thanks for commenting on this issue, it would be great if you could open a new issue in our repo with logs/detailed explanation of the issue you are hitting so we can diagnose what is going on since the issue described that the root of the thread seems to have been resolved--thanks!

**Comment by mabead** [comment]
I installed PowerShell 7 from [here](https://github.com/PowerShell/PowerShell/releases) and it fixed the problem for me.

**Comment by rjmholt** [comment]
> I installed PowerShell 7 from here and it fixed the problem for me.

Yeah, this likely means that the issue is what I think it is in https://github.com/PowerShell/vscode-powershell/issues/2538. Resolving the right dependency in .NET Core is much much easier, so we have a well-defined solution that works for PS 6 and 7.

**Comment by js82jumper** [comment]
I also ran into this on a completely clean install and can confirm that installing PowerShell 7 fixed mine as well.

**Comment by steveaf** [comment]
I had the same "language service could not be started" issue in VS Code.  I have both PowerShell and PowerShell Core 7 on Windows.  In both with elevated PowerShell commands I **set-executionpolicy unrestrected** and no longer have an issue.

**Comment by clouditgirl** [comment]
> > I had this exactly same issue. Disabling, enabling then reload solved it for me.
> 
> This did not work for me :(.

didn't work for me either.

**Comment by Meron-cloud** [comment]
Hello 
I have the same issue
![ps](https://user-images.githubusercontent.com/61019219/92048723-6f63c000-ed56-11ea-9b1e-535303692d07.JPG)

**Comment by SydneyhSmith** [comment]
@Meron-cloud thanks--looks like you may be hitting a new issue could you please open a new issue with the information requested in the template it would be really helpful if you could also attach the logs--instructions for how to do that are [here ](https://github.com/PowerShell/vscode-powershell/blob/master/docs/troubleshooting.md#providing-information-about-your-environment)
