### ISSUE TITLE
Unable to start PowerShell extension on Windows without PS 6+ installed

### ISSUE THREAD

**Issue by mohammedha** [PowerShell/vscode-powershell#2217]
Hi there,

After the the extension upgrade to 2019.9.0, I started to get the following error
```
30/09/2019 11:02:49 [NORMAL] - Visual Studio Code v1.38.1 64-bit
30/09/2019 11:02:49 [NORMAL] - PowerShell Extension v2019.9.0
30/09/2019 11:02:49 [NORMAL] - Operating System: Windows 64-bit
30/09/2019 11:02:49 [NORMAL] - Path specified by 'powerShellExePath' setting - '' - not found, reverting to default PowerShell path.
30/09/2019 11:03:15 [ERROR] - <ConsoleFeature>: Unable to instantiate; language client undefined.
```

Installed the previous version 2019.5 and was able to load the integrated terminal and run PS cmdlets

```
VERBOSE: 
#-- Console Encoding ---------------------------------------------------------
VERBOSE: System.Text.ASCIIEncoding
VERBOSE: 
#-- Updated PSModulePath to: -------------------------------------------------
VERBOSE: C:\Users\mohamed\Documents\WindowsPowerShell\Modules
VERBOSE: C:\Program Files\WindowsPowerShell\Modules
VERBOSE: C:\WINDOWS\system32\WindowsPowerShell\v1.0\Modules
VERBOSE: c:\Users\mohamed\.vscode\extensions\ms-vscode.powershell-2019.5.0\modules
VERBOSE: 
#-- Check required modules available -----------------------------------------
VERBOSE: Testing module availability PowerShellGet 
VERBOSE: Populating RepositorySourceLocation property for module PowerShellGet.
VERBOSE: Loading module from path 'C:\Program Files\WindowsPowerShell\Modules\PowerShellGet\2.2\PSModule.psm1'.
VERBOSE: Populating RepositorySourceLocation property for module PowerShellGet.
VERBOSE: Loading module from path 'C:\Program Files\WindowsPowerShell\Modules\PowerShellGet\2.1.4\PSModule.psm1'.
VERBOSE: Populating RepositorySourceLocation property for module PowerShellGet.
VERBOSE: Loading module from path 'C:\Program Files\WindowsPowerShell\Modules\PowerShellGet\2.0.4\PSModule.psm1'.
VERBOSE: Loading module from path 'C:\Program Files\WindowsPowerShell\Modules\PowerShellGet\1.0.0.1\PSModule.psm1'.
VERBOSE: PowerShellGet  found
```
Versions 
```
> code --list-extensions --show-versions
akamud.vscode-theme-onedark@2.1.0
bmuskalla.vscode-tldr@1.0.0
CoenraadS.bracket-pair-colorizer@1.0.61
Darfka.vbscript@1.0.4
DougFinke.vscode-PSStackoverflow@0.0.2
eamodio.gitlens@10.0.1
formulahendry.code-runner@0.9.14
ms-vscode-remote.remote-wsl@0.39.5
ms-vscode.powershell@2019.9.0
Shan.code-settings-sync@3.4.3
Tyriar.shell-launcher@0.3.0
```
```
> code -v
1.38.1
b37e54c98e1a74ba89e03073e5a3761284e3ffb0
x64

```

```
> $PSVersionTable

Name                           Value
----                           -----
PSVersion                      5.1.18362.145
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.18362.145
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1

```

[vscode-powershell.log](https://github.com/PowerShell/vscode-powershell/files/3671686/vscode-powershell.log)

**Comment by TylerLeonhardt** [comment]
Thanks for the info! Can you also [attach the logs](https://github.com/PowerShell/vscode-powershell/blob/master/docs/troubleshooting.md#providing-information-about-your-environment) here so we can get a better idea of what's going on?

**Comment by mohammedha** [comment]
uploaded to the original post

**Comment by TylerLeonhardt** [comment]
Can you attach the other log files as well? We're looking for a `PowerShellEditorServices` log file. Or is that the only file that appears in the directory? Please make sure you've turned on `Diagnostic` logging:

```
"powershell.developer.editorServicesLogLevel": "Diagnostic"
```

Also, this is not a requirement for the extension but I'm wondering - do you have PowerShell 6+ (aka PowerShell Core, aka `pwsh`) installed on your machine?

**Comment by Bummibaer** [comment]
I have the same issue, additionaly to the log above, get:

>  1.10.2019 10:45:51 [NORMAL] - Language server starting --
1.10.2019 10:45:51 [NORMAL] -     exe: C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe
1.10.2019 10:45:51 [NORMAL] -     args: c:\Users\foo\.vscode\extensions\ms-vscode.powershell-2019.9.0\modules\PowerShellEditorServices\Start-EditorServices.ps1 -HostName 'Visual Studio Code Host' -HostProfileId 'Microsoft.VSCode' -HostVersion '2019.9.0' -AdditionalModules @('PowerShellEditorServices.VSCode') -BundledModulesPath 'c:\Users\ADNetz\.vscode\extensions\ms-vscode.powershell-2019.9.0\modules' -EnableConsoleRepl -LogLevel 'Diagnostic' -LogPath 'c:\Users\ADNetz\.vscode\extensions\ms-vscode.powershell-2019.9.0\logs\1569919551-b833b993-4e56-4bc7-9a8f-cf4bec56ec0a1569919463806\EditorServices.log' -SessionDetailsPath 'c:\Users\ADNetz\.vscode\extensions\ms-vscode.powershell-2019.9.0\sessions\PSES-VSCode-9508-733185' -FeatureFlags @()
1.10.2019 10:45:52 [NORMAL] - powershell.exe started, pid: 17664
1.10.2019 10:45:52 [ERROR] - <ConsoleFeature>: Unable to instantiate; language client undefined.
1.10.2019 10:45:53 [NORMAL] - Language server started.
1.10.2019 10:45:53 [NORMAL] - {"languageServiceTransport":"NamedPipe","languageServicePipeName":"\\\\.\\pipe\\PSES_engwrsub.1dd","debugServiceTransport":"NamedPipe","status":"started","debugServicePipeName":"\\\\.\\pipe\\PSES_zundodvk.chg"}
1.10.2019 10:45:53 [NORMAL] - Connecting to language service on pipe \\.\pipe\PSES_engwrsub.1dd...
1.10.2019 10:45:53 [NORMAL] - Language service connected.
1.10.2019 10:46:25 [NORMAL] - Shutting down language client...
1.10.2019 10:46:25 [NORMAL] - Terminating PowerShell process...

**Comment by mohammedha** [comment]
> Can you attach the other log files as well? We're looking for a `PowerShellEditorServices` log file. Or is that the only file that appears in the directory? Please make sure you've turned on `Diagnostic` logging:
> 
> ```
> "powershell.developer.editorServicesLogLevel": "Diagnostic"
> ```
> 
> Also, this is not a requirement for the extension but I'm wondering - do you have PowerShell 6+ (aka PowerShell Core, aka `pwsh`) installed on your machine?

Unfortunately this is the only log file available even the log level is set to Diagnostic
I have PS 5.1.18362.145 only.


![2019-10-01_12h28_22](https://user-images.githubusercontent.com/4114872/65958303-f9205480-e446-11e9-9065-1399685d48ed.png)

**Comment by TylerLeonhardt** [comment]
@mohammedha do you work in an environment that is locked down via Group Policy or similar?

**Comment by mohammedha** [comment]
@TylerLeonhardt not really, also I am running Code as Admin.

**Comment by TylerLeonhardt** [comment]
Can you run this in a PowerShell session:
```pwsh
[System.Environment]::OSVersion
```

I'm curious what version of Windows you're on.

Also, can you do me a favor as a test? I'd like you to installed the latest version of PowerShell to see there's a problem in how we discover what PowerShell's are installed on the system.

You can grab the msi from here:
https://github.com/PowerShell/PowerShell#get-powershell

**Comment by OranguTech** [comment]
I'm having same issue as well:

(After trying disabling all over extensions, rebooting, running as admin)

```
10/2/2019 5:20:21 PM [NORMAL] - Path specified by 'powerShellExePath' setting - '' - not found, reverting to default PowerShell path.
10/2/2019 5:21:29 PM [ERROR] - <ConsoleFeature>: Unable to instantiate; language client undefined.
10/2/2019 5:21:48 PM [ERROR] - <ConsoleFeature>: Unable to instantiate; language client undefined.
10/2/2019 5:26:57 PM [NORMAL] - Shutting down language client...

```
Environment Info:

```
> [System.Environment]::OSVersion

Platform ServicePack Version      VersionString
-------- ----------- -------      -------------
 Win32NT             10.0.17763.0 Microsoft Windows NT 10.0.17763.0


C:\WINDOWS\system32> $PSVersionTable

Name                           Value
----                           -----
PSVersion                      5.1.17763.592
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.17763.592
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1

C:\WINDOWS\system32> code -v
1.38.1
b37e54c98e1a74ba89e03073e5a3761284e3ffb0
x64
C:\WINDOWS\system32> code --list-extensions --show-versions
dbaeumer.vscode-eslint@1.9.1
donjayamanne.githistory@0.4.6
DotJoshJohnson.xml@2.5.0
eamodio.gitlens@10.0.1
huizhou.githd@2.1.0
humao.rest-client@0.22.2
mechatroner.rainbow-csv@1.3.1
ms-azure-devops.azure-pipelines@1.157.4
ms-azuretools.vscode-apimanagement@0.1.1
ms-azuretools.vscode-azureappservice@0.16.0
ms-azuretools.vscode-azurefunctions@0.18.1
ms-azuretools.vscode-azurestorage@0.7.1
ms-azuretools.vscode-cosmosdb@0.11.0
ms-azuretools.vscode-docker@0.8.1
ms-mssql.mssql@1.6.0
ms-vscode-remote.remote-containers@0.74.0
ms-vscode-remote.remote-ssh@0.46.1
ms-vscode-remote.remote-ssh-edit@0.46.1
ms-vscode-remote.remote-ssh-explorer@0.46.1
ms-vscode-remote.remote-wsl@0.39.5
ms-vscode-remote.vscode-remote-extensionpack@0.17.0
ms-vscode.azure-account@0.8.4
ms-vscode.azurecli@0.4.6
ms-vscode.csharp@1.21.3
ms-vscode.powershell@2019.9.0
ms-vscode.vscode-node-azure-pack@0.0.9
ms-vsts.team@1.149.2
msazurermtools.azurerm-vscode-tools@0.7.0
redhat.vscode-yaml@0.5.3
stansw.vscode-odata@0.1.0
VisualStudioOnlineApplicationInsights.application-insights@0.4.2
vsciot-vscode.azure-iot-toolkit@2.10.0
yzhang.markdown-all-in-one@2.4.2
zhoufeng.json-helper@1.3.2
```

**Comment by OranguTech** [comment]
@TylerLeonhardt - (re)installing* current release version of 6 fixed it!

![image](https://user-images.githubusercontent.com/1691149/66091913-9dd18d80-e53e-11e9-945f-ae11514354ad.png)

*I previously had v6 installed but uninstalled a while back as there was no immediate benefit, and 7 is on the way...

**Comment by rjmholt** [comment]
> So how do I point the PSExtension to the v5 instance of PoSh?

You should be able to select it when you click on the PowerShell version in the bottom right hand corner

**Comment by mohammedha** [comment]
@TylerLeonhardt 
my OS version is 
Platform ServicePack Version      VersionString
-------- ----------- -------      -------------
 Win32NT             10.0.18362.0 Microsoft Windows NT 10.0.18362.0

Okay, I think you are right, the issue is discovering the PS version
After installing PS 6.2 and installing the latest extension version 2019.9 now it started to work 
attached my diagnostic logs

[Start-EditorServices-EditorServices.log](https://github.com/PowerShell/vscode-powershell/files/3685178/Start-EditorServices-EditorServices.log)
[vscode-powershell.log](https://github.com/PowerShell/vscode-powershell/files/3685179/vscode-powershell.log)
[EditorServices.log](https://github.com/PowerShell/vscode-powershell/files/3685180/EditorServices.log)

**Comment by OranguTech** [comment]
> > So how do I point the PSExtension to the v5 instance of PoSh?
> 
> You should be able to select it when you click on the PowerShell version in the bottom right hand corner

Thanks, I forgot about that GUI prompt.

I've verified it also works w/ PoSh 7 (Preview 4), without 6 installed.

**Comment by rjmholt** [comment]
> After installing PS 6.2 and installing the latest extension version 2019.9 now it started to work
attached my diagnostic logs

Drat! Ok, we shall fix

**Comment by kinwolfqc** [comment]
same problem here.  Cannot debug or run powershell DSC scripts anymore 

> "Cannot debug or run a PowerShell script until the PowerShell session has started. Wait for the PowerShell session to finish starting and try again."

**Comment by fekfoq259** [comment]
> same problem here. Cannot debug or run powershell DSC scripts anymore
> 
> > "Cannot debug or run a PowerShell script until the PowerShell session has started. Wait for the PowerShell session to finish starting and try again."
> 
> This started to happen after I installed PS 6 Core and then removed it. After reinstalling PS 6 Core it worked again.

I have same issuse. When I uninstall PowerShell 6 than VSCode can't use F5 or F8 run powershell srcipt. 

ms-vscode.powershell@2019.9.0
1.39.2
6ab598523be7a800d7f3eb4d92d7ab9a66069390
x64

PSVersion                      5.1.18362.145                                                    
PSEdition                      Desktop                                                          
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}                                          
BuildVersion                   10.0.18362.145                                                   
CLRVersion                     4.0.30319.42000                                                  
WSManStackVersion              3.0                                                              
PSRemotingProtocolVersion      2.3                                                              
SerializationVersion           1.1.0.1

**Comment by TylerLeonhardt** [comment]
This is fixed in #2238 just need to finish up that PR and then we'll do a release.

**Comment by tonipohl** [comment]
Hi, 
I ran into the same issue yesterday, the issue suddenly appeared. I could no longer run PS commands in VSCode with the PS extension, although I tried to reconfigure it properly. My solution was to upgrade PS 6.2.x to PS 7.0. Then it worked again.
dotnet tool update --global PowerShell
Tool 'powershell' was successfully updated from version '6.2.3' to version '7.0.0'.
https://docs.microsoft.com/en-us/dotnet/core/tools/global-tools
hth! br, Toni

**Comment by af4jm** [comment]
I've got PowerShell 7.0.3 & getting the same error as kinwolfqc & fekfoq259. Tried tonipohl's suggestion, instantly got a message that 7.0.3 was removed & reinstalled (obviously it wasn't since it finished in less than 1 second). No effect, still can't run or debug pwsh in VSCode, even though I have a pwsh terminal open in VS Code.

**Comment by Mayhem93** [comment]
Hey, first of all, sorry for commenting on a closed issue but I have something to add.

If you have WSL installed and run VScode in "wsl2 mode" you'll get this error message. I ran the close connection command the error of "powershell not found" is fixed. But I find it a bit annoying that I have to do that every time, because sometimes I work only with wsl2 mode of VScode, and sometimes with the "regular" mode in which case pwsh 7 is readily available.

**Comment by rjmholt** [comment]
If you install PowerShell on the WSL side, I assume the extension works for you as normal?

It sounds like we could improve the error message when PowerShell isn't found -- I think the only reason we haven't done that is that it's surprisingly rare; PowerShell is always there on Windows, and on other platforms people are unlikely to get the extension without already having installed PowerShell.

**Comment by Mayhem93** [comment]
@rjmholt After installing wsl2 (and the vscode extension for it), it automatically defaults everything to WSL, that's why I called it a "mode". I only recently started working with wsl2 in vscode. 

After removing the wsl2 connection (through the mentioned command):
* If i open vscode through the start menu, it shows that it's not in the "wsl2 mode".
* Opening it from a powershell cli is the same
* Opening vscode from wsl2 makes vscode automatically connect to wsl2 backend

After all this, it seems like vscode doesn't run in "wsl2 mode" anymore automatically, unless it's started from wsl2. These are my findings. It seems like it only does it *every time* initially after installing the wsl2 thingy.
