### ISSUE TITLE
Intellisense Hanging in Editor

### ISSUE THREAD

**Issue by GHartsfield** [PowerShell/vscode-powershell#2590]
Issue Type: <b>Bug</b>

As of today when I updated to 2020.3.1 there have been frequent intellisense hangs/crashes. I cannot seem to find a way to reproduce it reliably but it happens within a few minutes of reloading either the extension or vscode. Had been working consistently for about a week on the same project in the previous extension version with no issues. No other changes to the environment. Attached the error logs and editor services verbose output.

Extension version: 2020.3.1
VS Code version: Code 1.43.2 (0ba0ca52957102ca3527cf479571617f0de6ed50, 2020-03-24T07:38:38.248Z)
OS version: Windows_NT x64 10.0.18363

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-3350P CPU @ 3.10GHz (4 x 3100)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.95GB (21.95GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>

[editorServices.txt](https://github.com/PowerShell/vscode-powershell/files/4398066/editorServices.txt)
[1585437259-3a5b48de-f50f-46cc-9d7c-3cd4c1d40cee1585436631396.zip](https://github.com/PowerShell/vscode-powershell/files/4398067/1585437259-3a5b48de-f50f-46cc-9d7c-3cd4c1d40cee1585436631396.zip)

**Comment by TylerLeonhardt** [comment]
Thanks for the info! Can you please set the log level to `Diagnostic` and try to repro again? It looks like the log files in the zip are basically empty... I expected to see more if they were proper logs. This might be an indication that the issue could be elsewhere but we need to know more.

```json
"powershell.developer.editorServicesLogLevel": "Diagnostic"
```

**Comment by GHartsfield** [comment]
Thanks for the reply, I thought there wasn't much in the logs as well - unfortunately those were taken in diagnostic mode.  I have switched back over to the non-preview extension and the problem has gone away. Don't know if its relevant but I am using custom prefixes in the modules which your GetCommandSynopsisAsync refactor seemed to fix - now that I'm back in non-preview I have no intellisense issues but I do have issues with the module prefixes again.

**Comment by stevenebutler** [comment]
My intellisense doesn't work at all with the latest preview 2020.3.1, anywhere in my code base. I have dropped back to 2020.3.0 where it appears to work reasonably well.

**Comment by TylerLeonhardt** [comment]
@stevenebutler @GHartsfield I just published 2020.3.2 of PowerShell Preview. Can you give it a try and let me know how works for you? Thanks!

**Comment by TylerLeonhardt** [comment]
This is fixed in https://github.com/PowerShell/PowerShellEditorServices/pull/1248

**Comment by TylerLeonhardt** [comment]
I've received one report that said this issue was fixed so I'm going to close this. Let me know how it goes for you two!

**Comment by stevenebutler** [comment]
Hi yes, is fixed for me too - I did give a thumbs up to indicate this but you may not have seen it.

**Comment by TylerLeonhardt** [comment]
@stevenebutler thanks! Sorry I wasn't sure if that was  "it's fixed! " or "I'll try it out!" my bad.

**Comment by GHartsfield** [comment]
It appears I'm still having issues with this. It happens much less often (after a few hours rather than minutes). But I still can't seem to reliably reproduce it. Have attached new diagnostic log. The intellisense hang happened around 2:10pm. 

[2020.3.2.zip](https://github.com/PowerShell/vscode-powershell/files/4422849/2020.3.2.zip)

**Comment by stevenebutler** [comment]
Hi, I see similar lock ups with the editor intellisense after a period of it working. I'm sorry I'm unable to provide logs due to my employment agreement. A restart of the integrated console gets it working again so it's annoying but not completely detrimental.
