### ISSUE TITLE
Profile fails to load when `System.Windows.Forms` objects are used, hanging extension

### ISSUE THREAD

**Issue by baldieavenger** [PowerShell/vscode-powershell#3394]
Hey team,
Since the latest update, i'm not able to use the editor to run any code. Love that I wont get prompted to save now when running, not loving the fact the PowerShell session never completes now when running my auto loading profile (365 module signs in, which appear to be successful - Other than the latest ExchangeManagement module never popping out the creds prompt but I can work around using the lower version for now!)
All my modules pop up and sign ins are successful, but I cant figure out why the session hasn't finished to allow me to use the editor to run code now?
I've downgraded for now back to v2021.2.2 which lets me auto load my profile and sign in and let me carry on using the editor without issue.
![VSCodeSessionError](https://user-images.githubusercontent.com/39298966/120641065-1652c500-c46b-11eb-939c-44fc9c8b1ea2.jpg)

**Comment by andschwa** [comment]
Hi,

Could you please provide more [logging and environment information by following these steps](https://github.com/PowerShell/vscode-powershell/blob/master/docs/troubleshooting.md#providing-information-about-your-environment)?

Thanks!

**Comment by baldieavenger** [comment]
> Hi,
> 
> Could you please provide more [logging and environment information by following these steps](https://github.com/PowerShell/vscode-powershell/blob/master/docs/troubleshooting.md#providing-information-about-your-environment)?
> 
> Thanks!

Hiya! 

Here you go, wasn't sure which so you have all 3!

I updated to v2021.5.1, restarted, entered creds from the prompts and tried to run something using F5 from the editor again and got the same issue.

Thanks!
[VSCode-Logs-20210603..zip](https://github.com/PowerShell/vscode-powershell/files/6593231/VSCode-Logs-20210603.zip)

**Comment by andschwa** [comment]
All three is perfect, thanks!

**Comment by andschwa** [comment]
Ah, I see in the logs that this is with PowerShell 5.1. Can you try PowerShell 7 and see if it still repros?

**Comment by baldieavenger** [comment]
I can, but, it's not managed Enterprise wide so this wont help for everyone here that uses Code as well as 5.1 on our prod servers. Also, embarrassingly im not sure how to update Code to use Ps7....
Is 5.1 no longer supported?

**Comment by baldieavenger** [comment]
So this isnt an issue with Code v Version: 1.56.2 (system setup), which is annoying again as the EUC team decide to add this as a managed app, via a process which means they are out of date and I havent figured out how to kill it from my machine yet, but I will..... 
Id say you can close this, unless you want to dig in any further with 1.54.3?
(Ill also open another ticket about ExchangeManagementOnline v2.0.5 cred prompt never appearing!)

**Comment by baldieavenger** [comment]
Side note.... Now that im not prompted to save changes when using Editor, it doesnt run the code with the changes I made, unless I save it first. Is that intentional? I assumed it would allow me to run whatever was in that editor at that time, regardless of if id saved it or not?

**Comment by andschwa** [comment]
It should _only_ not be prompting for untitled files, and that should only be the case in VS Code Insiders right now. Otherwise that behavior is unchanged. What happened was that we added this default config for their upcoming feature: https://github.com/PowerShell/vscode-powershell/pull/3357/files

For PowerShell files, it is to set to prompt for `nonUntitledEditorsInActiveGroup` or, "all editors except those that are untitled."

**Comment by andschwa** [comment]
Sorry, haven't had a chance to look at the main part of this issue yet.

**Comment by baldieavenger** [comment]
No worries, I'm in the UK so the weekend has already started

**Comment by baldieavenger** [comment]
Happy Monday! Rearing to go to help out where I can for this!

**Comment by andschwa** [comment]
Hey! Sorry, I was on vacation this last week and am just now back today. I should get to this on Monday, currently just triaging everything.

**Comment by andschwa** [comment]
@baldieavenger I'm wondering if this has to do with the main PowerShell 5.1 bug https://github.com/PowerShell/vscode-powershell/issues/3395#issuecomment-859969488 that cropped up this release. Can you test this extension build? [PowerShell-insiders.vsix.zip](https://github.com/PowerShell/vscode-powershell/files/6650046/PowerShell-insiders.vsix.zip)

**Comment by baldieavenger** [comment]
Hi Andrew,
I tried this but it didnt help. I suspect though this is just my machine and something caused by a mis config on my side somewhere. I dont get the same issue on a server after updating to the latest VScode and PS and my local code is slowly breaking.... Intellisense doesnt work in the editor anymore eithe....
Plan to rebuild next week though and start from scratch so if no one else has raised this with you, feel free to close! No point spending time with just me if its just me!

**Comment by baldieavenger** [comment]
Hi Andrew,
Anything more you need from me to dig into this?
Thanks! 
John

**Comment by baldieavenger** [comment]
Something to add! I use a little Microsoft.VSCode_profile.ps1 which contains a pop out then invoke command so I can choose the ps1 profile I want to use at the time and its this causing the issue! 
If I just use my log in script as Microsoft.VSCode_profile.ps1 it auto loads, prompts, signs in and then has finished doing its thing! 
If I use my function to open and let me choose which one, it doesnt!
[Microsoft.VSCode_profile.txt](https://github.com/PowerShell/vscode-powershell/files/6749388/Microsoft.VSCode_profile.txt)

**Comment by andschwa** [comment]
Oh, that is helpful. I see your function uses `System.Windows.Forms` which I know is causing other issues too: https://github.com/PowerShell/vscode-powershell/issues/3410#issuecomment-860976636

**Comment by baldieavenger** [comment]
Looks like the same cause then for both of these too!
https://github.com/MicrosoftDocs/office-docs-powershell/issues/7895
https://github.com/PowerShell/vscode-powershell/issues/3396

**Comment by andschwa** [comment]
Ah, well, at least we know the problem. My understanding is that it may be difficult to fix due to the way `System.Windows.Forms` interoperates with a program's threading. But maybe https://github.com/PowerShell/PowerShellEditorServices/issues/1295 will fix it? We shall see...

**Comment by baldieavenger** [comment]
Thanks! Whilst I'm here...... Any ideas on another way I can open a dialogue box to ask me for a ps1 to load? Lol

**Comment by andschwa** [comment]
@rjmholt thinks that we may have missed a location in PSES where we are not using `ConfigureAwait(false)` which causes these issues with `System.Windows.Forms`, so it looks like a bug on our end that we need to investigate. Sadly we cannot think of another way to open a dialogue box (though I suppose you could just use a Y/N prompt on the terminal?)

**Comment by andschwa** [comment]
Hey @baldieavenger, could you test this dev build and let me know if it solves the issue? 
[powershell-preview-2021.8.1.zip](https://github.com/PowerShell/vscode-powershell/files/6957834/powershell-preview-2021.8.1.zip)

**Comment by baldieavenger** [comment]
Hi Andrew,
Installed and opened Code, prompted for my profile.ps1 and then starts to load but doesnt seem to actually open it and load anything.
I also dont get an option for the dropdown integrated terminal now when I did before, so I assume I wouldnt be able to hit f5 to run my script in the editor if it did load anyways (Unsure if thats helpful but thought id mention!) 

Logs attached.

Thanks!

John

[Logs-ms-vscode.powershell-preview-2021.8.1.zip](https://github.com/PowerShell/vscode-powershell/files/6961542/Logs-ms-vscode.powershell-preview-2021.8.1.zip)

**Comment by youngr137** [comment]
Ok so I installed the preview and tested with the simple HelloWorld.ps1 that I started with and that worked first time however I could not get it to start again (f5). There is an ETIMEDOUT logged in the output for the extension.  I have tried with other scripts that use System.Window.Forms and they all appear to do the same. That is run once on first start up of Visual Studio but can't be started again. Occasionally when a program exits instead of the normal prompt ( PS <current directory>>) I just get a PS > prompt. When this occurs I was able to start the program again and everything worked as I expected. Once in a while a minimised Console Window Host appeared on starting Visual Studio. I added log files. I did not see either of the 'occasional' events like the prompt stopping with PS or the Console window during the logged test run.
I don't appear to be able to upload log files. They just appear a text in the comment but perhaps they get uploaded on clicking comment?
[1628603130-5d2c9f62-1894-4d70-a6d2-fc956fc65b441628603105575.zip](https://github.com/PowerShell/vscode-powershell/files/6962323/1628603130-5d2c9f62-1894-4d70-a6d2-fc956fc65b441628603105575.zip)

**Comment by andschwa** [comment]
@baldieavenger I tested that build with your posted profile.ps1 and it seems to be working exactly as expected now. As @SeeminglyScience mentioned, there's an entirely separate upstream issue with VS Code that GUI windows are displayed _behind_ the VS Code window, and there's sadly nothing we as extension authors can do about it. So while debugging your profile, after I've stepped over the line which creates the GUI window, I then alt-tabbed to it (as it was behind the editor), selected a file, and then was able to continue debugging and hit a breakpoint after that code.

@youngr137 you are probably seeing the same thing. My guess it that it timed out because you never found the (rather hidden) dialogue window behind the editor.

**Comment by andschwa** [comment]
Here's that issue: #1175

**Comment by youngr137** [comment]
I am sure there is no hidden dialogue. I do see that when debugging with Visual Studio but the issue is that after working normally on first attempt the second run will timeout and give 10/08/2021 18:05:55 [ERROR] - Error on Debug Adapter: Error: connect ETIMEDOUT \\.\pipe\PSES_pmxwttse.nu3 on the output for the Powershell Extension. The code never gets to start under the debugger.

**Comment by baldieavenger** [comment]
Hi Both, 
Ive looked for Windows behind and everywhere else but this doesnt help me. Alt + Tab doesnt show anything open either.
My Microsoft.VSCode_profile.ps1 contains the choose file prompt.

[Microsoft.VSCode_profile.txt](https://github.com/PowerShell/vscode-powershell/files/6963263/Microsoft.VSCode_profile.txt)

That still seems to pop out for me in front and I can choose my "365AdminSignIns.ps1" to invoke, which is my previous version of "Microsoft.VSCode_profile.ps1" (connect to Exchange, Azure, SPO etc)

[365AdminSignIns.txt](https://github.com/PowerShell/vscode-powershell/files/6963315/365AdminSignIns.txt)


It starts and I can see its starting to connect, but at the point normally a pop up would happen which is a Microsoft authenticaiton page to enter credentials and verify via MFA if applicable (Im using a encrypted txt file would sign me in without input so I dont need to see it) its just freezing and not moving past this point. (Looks like line 6 in the attached 365AdminSignIns.txt - was a ps1 but cant attach ps1 here)
 
Its not that I need to see it or interactive with it but its being blocked from popping up and doing its own thing in the first place which then means it cant sign in.

Nothing in the debug console or output or problems tabs either.

[Logs2-ms-vscode.powershell-preview-2021.8.1.zip](https://github.com/PowerShell/vscode-powershell/files/6963286/Logs2-ms-vscode.powershell-preview-2021.8.1.zip)

This does work fine in ISE with the pop up, file selection and then invoke.

My 365AdminSignIns.txt file does work perfectly too if I move the contents into "Microsoft.VSCode_profile.ps1"

:(

**Comment by andschwa** [comment]
> 10/08/2021 18:05:55 [ERROR] - Error on Debug Adapter: Error: connect ETIMEDOUT \.\pipe\PSES_pmxwttse.nu3

Well that's strange, and seems very different 😢

**Comment by andschwa** [comment]
> My 365AdminSignIns.txt file does work perfectly too if I move the contents into "Microsoft.VSCode_profile.ps1"

Ok, wait, so at this point the issue is _only_ happening when `Connect-ExchangeOnline -UserPrincipalName adm-User@domain.com -ShowProgress $true` (which presumably uses `System.Windows.Forms`) is piped e.g. `"&'$file'" | invoke-expression`, is that right?

@rjmholt any ideas?

**Comment by andschwa** [comment]
@youngr137 You seem to be seeing the same thing as what was just reported in #3505

**Comment by Abax378** [comment]
> Hey @baldieavenger, could you test this dev build and let me know if it solves the issue?
> [powershell-preview-2021.8.1.zip](https://github.com/PowerShell/vscode-powershell/files/6957834/powershell-preview-2021.8.1.zip)

I disabled the current PS extension in VS Code and loaded the .vsix file referenced above. The terminal posts a PID like this

PID: 15156

then keeps posting the same line in a repeating loop. Eventually, VS Code reports that loading PS is taking longer than usual and sometimes reports it could not load the language. Killed the terminal window and started a new one, but subsequent terminals don't try to load PS, so no effect. Re-booted Windows 10, tried again, same result.

Debugger won't run without PS, so unable to test.

I'm running the latest update for VS Code:

Version: 1.59.0 (system setup)
Commit: 379476f0e13988d90fab105c5c19e7abc8b1dea8
Date: 2021-08-04T23:13:12.822Z
Electron: 13.1.7
Chrome: 91.0.4472.124
Node.js: 14.16.0
V8: 9.1.269.36-electron.0
OS: Windows_NT x64 10.0.19042

**Comment by andschwa** [comment]
@Abax378

> I disabled the current PS extension in VS Code and loaded the .vsix file referenced above. The terminal posts a PID like this
> 
> PID: 15156
> 
> then keeps posting the same line in a repeating loop.

It is waiting for a debugger to be attached to the PowerShell process. That is due to a user setting:
```json
"powershell.developer.editorServicesWaitForDebugger": true,
```

Please set that to `false` instead and try again!

**Comment by Abax378** [comment]
> ```json
> "powershell.developer.editorServicesWaitForDebugger": true,
> ```

Did that. Debugger works as expected several times in a row. Same result with a restart of VS Code.

**Comment by baldieavenger** [comment]
I didnt have this setting so added it, if set to true I get either PID:0 7836, PID: 22228, PID: 14684, PID: 16512 when opening. (Is it meant to be different every time? Should I even be looking to add this and let you know what it does??) 
If set to fale, I get the same behaviour which is as you asked @andschwa above

**Comment by andschwa** [comment]
> I didnt have this setting so added it, if set to true I get either PID:0 7836, PID: 22228, PID: 14684, PID: 16512 when opening. (Is it meant to be different every time? Should I even be looking to add this and let you know what it does??)

This setting instructs the extension to wait for a debugger to be attached to the PowerShell process that it starts. That's why it's emitting the PID (which is different every time because new processes each have a new Process ID). It's used by developers for debugging the extension. Unless you _want_ to attach a debugger to the extension's PowerShell process, leave it set to `false`.

> I get the same behaviour which is as you asked @andschwa above

Can you state what that behavior is? Got a lot of issues and discussions happening, trying to keep this all straight is hard.

**Comment by baldieavenger** [comment]
No problem! 
After using [Microsoft.VSCode_profile.txt](https://github.com/PowerShell/vscode-powershell/files/6964582/Microsoft.VSCode_profile.txt) to open a prompt to allow me to select [365AdminSignIns.txt](https://github.com/PowerShell/vscode-powershell/files/6964584/365AdminSignIns.txt) which should auto sign me in to Exchange Online, I dont get the authentication box pop up whih then passes through my creds to sign me in.

**Comment by andschwa** [comment]
Instead of:

```powershell
    $file = Get-FileName -initialDirectory "C:\Users\USER\PATH\Documents\WindowsPowerShell"

   "&'$file'" | invoke-expression
```

Can you try:

```powershell
    $file = Get-FileName -initialDirectory "C:\Users\USER\PATH\Documents\WindowsPowerShell"

   & $file
```

**Comment by baldieavenger** [comment]
No change :(

**Comment by andschwa** [comment]
You're certain you've uninstalled the PowerShell extension from the marketplace and manually installed the VSIX I posted? I can no longer reproduce your issue with the dev build I posted, while I could reproduce it from the marketplace version. What version are you seeing on startup in the integrated console?

**Comment by baldieavenger** [comment]
I think so! 
![image](https://user-images.githubusercontent.com/39298966/128937949-d861ce60-4d4f-48d5-9f23-f3a4f0f63447.png)

This is interesting though, if I skip `Connect-ExchangeOnline -UserPrincipalName adm-User@domain.com -ShowProgress $true,` the next one to pop out is `Connect-SPOService -Url "https://domain-admin.sharepoint.com"` and this one _does_ pop out and let me enter my credentials.

**Comment by baldieavenger** [comment]
I tried changing `Connect-ExchangeOnline -UserPrincipalName adm-User@domain.com -ShowProgress $true` to `$cred = Get-Credential
Connect-ExchangeOnline -Credential $cred -ShowProgress $false`
This allows me to type my creds in the terminal and I wondered if that would mean it doesnt need to open the browser to authenticate, but its still the same so it must try and use tha pop up browser to authenticate regardless of what I do.

**Comment by andschwa** [comment]
Since the original bug in this issue is fixed, and that fix is now merged and will be in the next release, I will mark this issue as resolved. For your new problem, could you kindly open a new issue? You may want to wait until the extension is updated so you can try to reproduce it...take a look on Monday!

**Comment by baldieavenger** [comment]
I mean, its the same issue just worked through symptoms and the Beta isnt working for me as mentioned and after trying everything requested and providing all the logs but hey ho....
Ill come back if I still have issues and can confirm a colleague has the same issues after we update on Monday. Thanks!

**Comment by andschwa** [comment]
So, your issue goes away when you execute the code directly in your profile script, right? It now only fails when it's executed through `"&'$file'" | invoke-expression`? That seems to me to be a completely separate (albeit obviously still extant and annoying! I know) issue from the the bug around `System.Windows.Forms`.

**Comment by strickdd** [comment]
> 
> 
> Hey @baldieavenger, could you test this dev build and let me know if it solves the issue?
> [powershell-preview-2021.8.1.zip](https://github.com/PowerShell/vscode-powershell/files/6957834/powershell-preview-2021.8.1.zip)

@andschwa I installed the preview linked and initial tests have allowed me to debug as expected. I'll continue to run some tests today. If debugging fails again, should I open a new issue or is there one I can reference since this has been closed?

**Comment by rjmholt** [comment]
> If debugging fails again, should I open a new issue or is there one I can reference since this has been closed?

If it fails again it's probably a new (if related) problem, so worth a new issue for fresh discussion

**Comment by baldieavenger** [comment]
> So, your issue goes away when you execute the code directly in your profile script, right? It now only fails when it's executed through `"&'$file'" | invoke-expression`? That seems to me to be a completely separate (albeit obviously still extant and annoying! I know) issue from the the bug around `System.Windows.Forms`.

It always worked when executing the code directly, I've only ever had the problem when using the `"&'$file'" | invoke-expression` but ill give it a try, just in case when the new version is released! 
Thanks.

**Comment by andschwa** [comment]
> > So, your issue goes away when you execute the code directly in your profile script, right? It now only fails when it's executed through `"&'$file'" | invoke-expression`? That seems to me to be a completely separate (albeit obviously still extant and annoying! I know) issue from the the bug around `System.Windows.Forms`.
> 
> It always worked when executing the code directly, I've only ever had the problem when using the `"&'$file'" | invoke-expression` but ill give it a try, just in case when the new version is released!
> Thanks.

It's out! Give it a go. This particular issue seems like something else is going on that Rob and I need to debug with you. That line of PowerShell itself is confusing, as it's first invoking the file `$file` (the [`&`](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_operators?view=powershell-7.1#call-operator-) says "run this as a script") and then taking the result of that and piping it to [`Invoke-Expression`](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.utility/invoke-expression?view=powershell-7.1), which I mean is a thing you can do, but what are you expecting out of it? That line of code is executing `$file` and then executing its results as PowerShell code.

**Comment by strickdd** [comment]
> 
> 
> > If debugging fails again, should I open a new issue or is there one I can reference since this has been closed?
> 
> If it fails again it's probably a new (if related) problem, so worth a new issue for fresh discussion

Thought things were working well, but started having issues. Boiled it down to the simplest steps I could.
https://github.com/PowerShell/vscode-powershell/issues/3522

**Comment by baldieavenger** [comment]
> > > So, your issue goes away when you execute the code directly in your profile script, right? It now only fails when it's executed through `"&'$file'" | invoke-expression`? That seems to me to be a completely separate (albeit obviously still extant and annoying! I know) issue from the the bug around `System.Windows.Forms`.
> > 
> > 
> > It always worked when executing the code directly, I've only ever had the problem when using the `"&'$file'" | invoke-expression` but ill give it a try, just in case when the new version is released!
> > Thanks.
> 
> It's out! Give it a go. This particular issue seems like something else is going on that Rob and I need to debug with you. That line of PowerShell itself is confusing, as it's first invoking the file `$file` (the [`&`](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_operators?view=powershell-7.1#call-operator-) says "run this as a script") and then taking the result of that and piping it to [`Invoke-Expression`](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.utility/invoke-expression?view=powershell-7.1), which I mean is a thing you can do, but what are you expecting out of it? That line of code is executing `$file` and then executing its results as PowerShell code.

@andschwa This is fixed with the latest update today! 
v2021.9.0 and I can use the original Microsoft.VSCode_profile.ps1 with the `"&'$file'" | invoke-expression` and my pop up comes out, in front of my other windows and I can then navigate and choose another .ps1 with my profile in, which then does load!

**Comment by andschwa** [comment]
Awesome! So glad to hear that @baldieavenger.
