### ISSUE TITLE
v2024.2.0: PowerShell Terminal Fails to Load Due to PSES change to non-Windows-trusted Certificate

### ISSUE THREAD

**Issue by cyrkin** [PowerShell/vscode-powershell#4974]
### Prerequisites

- [X] I have written a descriptive issue title.
- [X] I have searched all [_open and closed_ issues](https://github.com/PowerShell/vscode-powershell/issues?q=is%3Aissue) to ensure it has not already been reported.
- [X] I have read the [troubleshooting](https://github.com/PowerShell/vscode-powershell/blob/main/docs/troubleshooting.md) guide.
- [X] I am sure this issue is with the _extension itself_ and does not reproduce in a standalone [PowerShell](https://github.com/PowerShell/PowerShell/issues/new/choose) instance.
- [X] I have verified that I am using the latest version of Visual Studio Code and the PowerShell extension.
- [x] If this is a security issue, I have read the [security issue reporting guidance](https://github.com/PowerShell/vscode-powershell/blob/main/SECURITY.md).

### Summary

Hello,
Since the extension updated itself to V 2024.2.0, I can't use the integrated Powershell terminal of my VS Code anymore, it won't load.
My ExecutionPolicy is set by GPO to AllSigned : it has always been like that, it worked like that, and it's not planned to change.
It's like the code in PSReadLine.format.ps1xml is now signed using an unapproved certificate on my side, or it tries desperately to force the ExecutionPolicy to change, which it did not do before.

When I finally kill the terminal, here's the output :

```
[Error - 8:47:47 AM] Microsoft.PowerShell.EditorServices.Services.PowerShell.Host.PsesInternalHost: Unable to load PSReadLine. Will fall back to legacy readline implementation. - System.Management.Automation.CmdletInvocationException: Des erreurs se sont produites lors du chargement du fichier de données de format : 
C:\Users\XXX\.vscode\extensions\ms-vscode.powershell-2024.2.0\modules\PSReadLine\2.4.0\PSReadLine.format.ps1xml, , C:\Users\XXX\.vscode\extensions\ms-vscode.powershell-2024.2.0\modules\PSReadLine\2.4.0\PSReadLine.format.ps1xml : le fichier a été ignoré en raison de l’exception de validation suivante : Impossible de charger le fichier C:\Users\XXX\.vscode\extensions\ms-vscode.powershell-2024.2.0\modules\PSReadLine\2.4.0\PSReadLine.format.ps1xml. Une chaîne de certificats a été traitée mais s’est terminée par un certificat racine qui n’est pas approuvé par le fournisseur d’approbation..
 ---> System.Management.Automation.RuntimeException: Des erreurs se sont produites lors du chargement du fichier de données de format : 
C:\Users\XXX\.vscode\extensions\ms-vscode.powershell-2024.2.0\modules\PSReadLine\2.4.0\PSReadLine.format.ps1xml, , C:\Users\XXX\.vscode\extensions\ms-vscode.powershell-2024.2.0\modules\PSReadLine\2.4.0\PSReadLine.format.ps1xml : le fichier a été ignoré en raison de l’exception de validation suivante : Impossible de charger le fichier C:\Users\XXX\.vscode\extensions\ms-vscode.powershell-2024.2.0\modules\PSReadLine\2.4.0\PSReadLine.format.ps1xml. Une chaîne de certificats a été traitée mais s’est terminée par un certificat racine qui n’est pas approuvé par le fournisseur d’approbation..

   à System.Management.Automation.Runspaces.InitialSessionState.ThrowTypeOrFormatErrors(String resourceString, String errorMsg, String errorId)
   à System.Management.Automation.Runspaces.InitialSessionState.UpdateFormats(ExecutionContext context, Boolean update)
   à System.Management.Automation.Runspaces.InitialSessionState.Bind_UpdateFormats(ExecutionContext context, Boolean updateOnly)
   à System.Management.Automation.Runspaces.InitialSessionState.Bind(ExecutionContext context, Boolean updateOnly, PSModuleInfo module, Boolean noClobber, Boolean local)
   à System.Management.Automation.Runspaces.InitialSessionState.Bind(ExecutionContext context, Boolean updateOnly)
   à Microsoft.PowerShell.Commands.ModuleCmdletBase.LoadModuleManifest(String moduleManifestPath, ExternalScriptInfo manifestScriptInfo, Hashtable data, Hashtable localizedData, ManifestProcessingFlags manifestProcessingFlags, Version minimumVersion, Version maximumVersion, Version requiredVersion, Nullable`1 requiredModuleGuid, ImportModuleOptions& options, Boolean& containedErrors)
   --- Fin de la trace de la pile d'exception interne ---
   à System.Management.Automation.Runspaces.PipelineBase.Invoke(IEnumerable input)
   à System.Management.Automation.PowerShell.Worker.ConstructPipelineAndDoWork(Runspace rs, Boolean performSyncInvoke)
   à System.Management.Automation.PowerShell.Worker.CreateRunspaceIfNeededAndDoWork(Runspace rsToUse, Boolean isSync)
   à System.Management.Automation.PowerShell.CoreInvokeHelper[TInput,TOutput](PSDataCollection`1 input, PSDataCollection`1 output, PSInvocationSettings settings)
   à System.Management.Automation.PowerShell.CoreInvoke[TInput,TOutput](PSDataCollection`1 input, PSDataCollection`1 output, PSInvocationSettings settings)
   à System.Management.Automation.PowerShell.Invoke(IEnumerable input, PSInvocationSettings settings)
   à Microsoft.PowerShell.EditorServices.Services.PowerShell.Utility.PowerShellExtensions.InvokeAndClear(PowerShell pwsh, PSInvocationSettings invocationSettings)
   à Microsoft.PowerShell.EditorServices.Services.PowerShell.Console.PSReadLineProxy.LoadAndCreate(ILoggerFactory loggerFactory, String bundledModulePath, PowerShell pwsh)
   à Microsoft.PowerShell.EditorServices.Services.PowerShell.Host.PsesInternalHost.TryLoadPSReadLine(PowerShell pwsh, EngineIntrinsics engineIntrinsics, IReadLine& psrlReadLine) | 
[Error - 8:47:47 AM] Microsoft.PowerShell.EditorServices.Services.PowerShell.Host.PsesInternalHost: Error occurred calling 'Set-ExecutionPolicy -Scope Process -ExecutionPolicy Unrestricted -Force' - System.Management.Automation.CmdletInvocationException: Windows PowerShell a correctement mis à jour votre stratégie d’exécution, mais ce paramétrage est remplacé par une stratégie définie dans un contexte plus spécifique. Votre environnement va donc conserver sa stratégie d’exécution actuelle, AllSigned. Tapez « Get-ExecutionPolicy -List » pour afficher les paramètres de stratégie d’exécution. Pour plus d’informations, voir « Get-Help Set-ExecutionPolicy ». ---> System.Security.SecurityException: Erreur de sécurité.
   à System.Management.Automation.MshCommandRuntime.ThrowTerminatingError(ErrorRecord errorRecord)
   --- Fin de la trace de la pile d'exception interne ---
   à System.Management.Automation.Runspaces.PipelineBase.Invoke(IEnumerable input)
   à System.Management.Automation.PowerShell.Worker.ConstructPipelineAndDoWork(Runspace rs, Boolean performSyncInvoke)
   à System.Management.Automation.PowerShell.Worker.CreateRunspaceIfNeededAndDoWork(Runspace rsToUse, Boolean isSync)
   à System.Management.Automation.PowerShell.CoreInvokeHelper[TInput,TOutput](PSDataCollection`1 input, PSDataCollection`1 output, PSInvocationSettings settings)
   à System.Management.Automation.PowerShell.CoreInvoke[TInput,TOutput](PSDataCollection`1 input, PSDataCollection`1 output, PSInvocationSettings settings)
   à System.Management.Automation.PowerShell.Invoke(IEnumerable input, PSInvocationSettings settings)
   à Microsoft.PowerShell.EditorServices.Services.PowerShell.Utility.PowerShellExtensions.InvokeAndClear(PowerShell pwsh, PSInvocationSettings invocationSettings)
   à Microsoft.PowerShell.EditorServices.Services.PowerShell.Utility.PowerShellExtensions.SetCorrectExecutionPolicy(PowerShell pwsh, ILogger logger) | Policy='Unrestricted'
[Warn  - 8:52:46 AM] OmniSharp.Extensions.LanguageServer.Server.LspServerOutputFilter: Tried to send request or notification before initialization was completed and will be sent later OmniSharp.Extensions.JsonRpc.RequestCancelled | @Request='OmniSharp.Extensions.JsonRpc.RequestCancelled'
[Error - 10:48:27 AM] Server initialization failed.
  Message: Pending response rejected since connection got disposed
  Code: -32097 
[Error - 10:48:27 AM] Connection to PowerShell Editor Services (the Extension Terminal) was closed. See below prompt to restart!
[Error - 10:48:27 AM] PowerShell Editor Services Client client: couldn't create connection to server.
  Message: Pending response rejected since connection got disposed
  Code: -32097
```

I rolled back to version 2024.0.0 and it works again.

### PowerShell Version

```console
Name                           Value
----                           -----
PSVersion                      5.1.19041.4170
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.19041.4170
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1

Name             : ConsoleHost
Version          : 5.1.19041.4170
InstanceId       : 86e284ae-6000-426e-aa83-129c82a8b98b
UI               : System.Management.Automation.Internal.Host.InternalHostUserInterface
CurrentCulture   : fr-FR
CurrentUICulture : fr-FR
PrivateData      : Microsoft.PowerShell.ConsoleHost+ConsoleColorProxy
DebuggerEnabled  : True
IsRunspacePushed : False
Runspace         : System.Management.Automation.Runspaces.LocalRunspace
```

### Visual Studio Code Version

```console
1.88.1
e170252f762678dec6ca2cc69aba1570769a5d39
x64
```

### Extension Version

```console
ms-vscode.powershell@2024.2.0
```

### Steps to Reproduce

1. Open VS Code and wait for the Integrated Powershell Terminal to load and wait for prompt
2. It never happens and stays like
```
PowerShell Extension v2024.2.0
Copyright (c) Microsoft Corporation.

https://aka.ms/vscode-powershell
Type 'help' to get help.
```
3. Kill the terminal to see the output

**Comment by SebCT** [comment]
Since 2024.2.0 some components of the module are signed with a untrusted certificate - here is the output with sigcheck from Sysinternals, also affects AppLocker if you use application allowlisting:

**Signers: Microsoft Azure Code Sign
Cert Status:    The revocation status of the certificate or one of the certificates in the certificate chain is unknown., Error 65536 (0x10000), The revocation status of the certificate or one of the certificates in the certificate chain is either offline or stale.**
                Valid Usage:    1.3.6.1.4.1.311.91.1.1, Code Signing
                Cert Issuer:    AME CS CA 01
                Serial Number:  36 00 00 01 DF 73 81 97 16 BE 32 FD 0D 00 02 00 00 01 DF
                Thumbprint:     1226440E939A24EB202C2A517CE13F8326EFDE60
                Algorithm:      sha256RSA
                Valid from:     03:33 20.01.2024
                Valid to:       03:33 19.01.2025
**AME CS CA 01
                Cert Status:    The certificate or certificate chain is based on an untrusted root., The revocation status of the certificate or one of the certificates in the certificate chain is unknown., The revocation status of the certificate or one of the certificates in the certificate chain is either offline or stale.**
                Valid Usage:    KDC Auth, Server Auth, Client Auth, Enrollment Agent, 1.3.6.1.4.1.311.21.6, Document Signing, 1.3.6.1.4.1.311.21.6, OCSP Signing, IPSEC IKE Intermediate, DNS Server, EFS Recovery, EFS, Private Key Archival, Smartcard Logon, 1.3.6.1.4.1.311.20.2.3, Code Signing, 1.3.6.1.4.1.311.91.1.1, 1.3.6.1.4.1.311.91.2.1, 1.3.6.1.4.1.311.91.3.1, 1.3.6.1.4.1.311.91.5.1, 1.3.6.1.4.1.311.91.4.1, 1.3.6.1.4.1.311.91.4.2
                Cert Issuer:    **ameroot**
                Serial Number:  1F 00 00 00 51 EA 8F F6 9C 73 0C A8 3B 00 00 00 00 00 51
                Thumbprint:     E3981E455AAFF0C851FF1D3C4EF41EE6A4C087F5
                Algorithm:      sha256RSA
                Valid from:     20:44 21.05.2021
                Valid to:       20:54 21.05.2026
           **ameroot**
                **Cert Status:    The certificate or certificate chain is based on an untrusted root.**
                Valid Usage:    All
                Cert Issuer:    ameroot
                Serial Number:  25 DA CB 55 C9 C6 77 81 40 9E 56 94 82 DE 4D FE
                Thumbprint:     413E8AAC6049924B178BA636CBAF3963CCB963CD
                Algorithm:      sha256RSA
                Valid from:     00:52 25.05.2016
                Valid to:       00:57 25.05.2026
                
 PLaese MS fix this asap und sign this with trusted root CA - workaround is now to revert to V2024.0.0 - even the newer prerelease version has the problem with untrusted CA

**Comment by andyleejordan** [comment]
No certificates are trusted on your machine by default. They are signed with updated certificates, you will need to trust those when running AllSigned.

**Comment by andyleejordan** [comment]
See more info here: https://github.com/PowerShell/vscode-powershell/issues/3741#issuecomment-1036475665

**Comment by SebCT** [comment]
> No certificates are trusted on your machine by default. They are signed with updated certificates, you will need to trust those when running AllSigned.

That's not true - there is a list of Trusted root certificates which gets updated by Microsoft and Windows does download them automatically. 

That Root certificate ameroot is mit an official root certificate - so you have problems with AppLocker.

Issue is not resolved.

**Comment by cyrkin** [comment]
> > No certificates are trusted on your machine by default. They are signed with updated certificates, you will need to trust those when running AllSigned.
> 
> That's not true - there is a list of Trusted root certificates which gets updated by Microsoft and Windows does download them automatically.
> 
> That Root certificate ameroot is not an official root certificate - so you have problems with AppLocker.
> 
> Issue is not resolved.

Couldn't agree more.

**Comment by SebCT** [comment]
> This issue has been labeled as resolved, please verify the provided fix (or other reason).

Not resolved yet

**Comment by JustinGrote** [comment]
@andyleejordan I can reproduce this on a clean Win11 box. The signing cert for PSES changed with the latest release, and it's not one that's trusted by Windows by default. Does this have to do with the build changes you made perhaps?

![image](https://github.com/PowerShell/vscode-powershell/assets/15258962/127af79b-8a4a-4f4d-86c0-6a6681e707f2)

**Comment by andyleejordan** [comment]
Ahh well that was embarassing. There was a typo in our pipeline that lead to a silent failure to use the correct certificate, so it defaulted to "Microsoft Azure Code Sign" instead of what it was supposed to be set to, "Microsoft Corporation." And that only shows up as a problem in particular circumstances (as you all have found). Hotfix release is on its way with this resolved. Thanks @JustinGrote for pointing that out. https://github.com/PowerShell/vscode-powershell/pull/4977

**Comment by andyleejordan** [comment]
Ok v2024.2.1 is out and fixes this. Sorry!

**Comment by JustinGrote** [comment]
Confirmed Fixed in my demo enviroment with `AllSigned` on.

**Comment by cyrkin** [comment]
Confirmed fixed with v2024.2.1 and _AllSigned_ on.
Big thanks to everyone who helped resolve the issue.

**Comment by JustinGrote** [comment]
@cyrkin thank you for persisting with additional information beyond our initial recommendation! Otherwise we wouldn't have caught it.

**Comment by andyleejordan** [comment]
Exactly. There _have_ been recurring issues with `AllSigned` in the past, so it took some extra digging to figure out what happened here. The specified key was right...the field was mistyped/copied as `signing_environment` instead of `signing_profile` and then just silently defaulted to the wrong key. Oh YAML.

**Comment by SebCT** [comment]
Thanks, working nearly perfect except one DLL: AppLocker is still having a problem with the certificate(s) and counter signing of this file here:

.vscode\extensions\ms-vscode.powershell-2024.2.1\modules\powershelleditorservices\bin\common\System.Reactive.dll

The DLL "System.Reactive.dll" is counter signed from yesterday with an "Microsoft 3rd party certificate", but also countersigned from the past in 2023, which worked perfect in the preious version 2024.0.0 - could you please investigate this an sign it with only one certificate/counter signing? It's important to allowlist this DLL with publisher rule in AppLocker - thanks in advance.

**Comment by andyleejordan** [comment]
I noticed that when setting this up actually, and unfortunately the `System.Reactive.dll` that's being restored from NuGet (version 6.0.0) is not first-party signed by "Microsoft Corporation" but by "Reactive Extensions for .NET (.NET Foundation)" so I _have_ to dual-sign it as "Microsoft 3rd Party Application Component".

**Comment by SebCT** [comment]
I see, but could the security engineers at Microsoft take a look because of AppLocker Application Allowlisting? Because with this new counter signed DLL a publisher rule doesn't work anymore, with the System.Reactive.dll from V2024.0.0 it works perfect - and all the other DLLs from the new V2024.2.1 work perfect with publisher rules, too. Thanks in advance, would be very happy when this issue could be resolved, security is very important for us ☺️

**Comment by JustinGrote** [comment]
@andyleejordan is the Reactive DLL a direct dependency or something transient from `csharp-language-server`?

**Comment by JustinGrote** [comment]
Also, doing a sigcheck looks like the DLL itself hasn't changed in PSES from 2024.2.0 from 2024.3.2, so was this just a new detection that was a previous mis-signing?
![image](https://github.com/PowerShell/vscode-powershell/assets/15258962/3457ede2-ac1b-4ece-8c57-49bc36154bbe)

**Comment by JustinGrote** [comment]
As an aside, I found the reference to `System.Reactive` which @TylerLeonhardt added 4 years ago
C:\Users\JGrote\Projects\PowerShellEditorServices\test\PowerShellEditorServices.Test.E2E\Processes\ServerProcess.cs

While we could unwind that, It is also referenced in OmniSharp.Extensions.JsonRPC as a transitive dependency
```
      "OmniSharp.Extensions.JsonRpc": {
        "type": "Transitive",
        "resolved": "0.19.9",
        "contentHash": "utFvrx9OYXhCS5rnfWAVeedJCrucuDLAOrKXjohf/NOjG9FFVbcp+hLqj9Ng+AxoADRD+rSJYHfBOeqGl5zW0A==",
        "dependencies": {
          "MediatR": "8.1.0",
          "Microsoft.Extensions.DependencyInjection": "6.0.1",
          "Microsoft.Extensions.Logging": "6.0.0",
          "Nerdbank.Streams": "2.10.69",
          "Newtonsoft.Json": "13.0.3",
          "OmniSharp.Extensions.JsonRpc.Generators": "0.19.9",
          "System.Collections.Immutable": "5.0.0",
          "System.Reactive": "6.0.0",
          "System.Threading.Channels": "6.0.0"
        }
``` 

So we wouldn't be able to remove the assembly due to that entrenched dependency.

**Comment by SebCT** [comment]
> Also, doing a sigcheck looks like the DLL itself hasn't changed in PSES from 2024.2.0 from 2024.3.2, so was this just a new detection that was a previous mis-signing? ![image](https://private-user-images.githubusercontent.com/15258962/323775419-3457ede2-ac1b-4ece-8c57-49bc36154bbe.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM2MzA4MzcsIm5iZiI6MTcxMzYzMDUzNywicGF0aCI6Ii8xNTI1ODk2Mi8zMjM3NzU0MTktMzQ1N2VkZTItYWMxYi00ZWNlLThjNTctNDliYzM2MTU0YmJlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDIwVDE2Mjg1N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQxZTYxYTRjNWQzNzBkMTgxNGI0NTQxNjBmM2NiZjcxMzlmMWU4MTFlZDhiNmI3MGRhMjNmZmI3ZWViOWViMWMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.LpZWYc9n9nicAqCnWB4-Tk5cBc7kbz6ZmuQzIPeMRRE)

As i can confirm, the former version 2024.2.0 and the pre-release version 2024.3.2 have the false ameroot certificate. 

The DLL's of Hotfix Version 2024.2.1 are signed correctly, except that one DLL "System.Reactive.DLL" - but in version 2024.0.0 the DLL works with publisher rule in AppLocker. So the best would be if the System.Reactive.DLL in 2024.2.1 has the same signing as in 2024.0.0 where it works perfectly - ideally it's the same DLL because of no code change inside the DLL?

**Comment by JustinGrote** [comment]
The Reactive DLL hasn't changed but it may have been being incorrectly signed as Microsoft First Party when it is in fact Microsoft Third party, that was my main query to @andyleejordan that may have been "fixed" but now breaks the ability for the extension to be wholly "pre-signed" on windows systems.

This is more of a legal issue than a technical one, so I have to defer to Andy as to whether that DLL can continue to be signed as it was before since it hasn't changed, but future versions may still have the problem anyways.

**Comment by JustinGrote** [comment]
Reopening the issue to address `System.Reactive` signing status.

**Comment by andyleejordan** [comment]
You've written it out exactly Justin. When switching to the new signing system, it detected that `System.Reactive.dll` is Microsoft Community and signed as such, and wouldn't let me sign it as first-party Microsoft Corporation. It was an error that it was previously, and allowed by a system that I no longer have access to. However, all the OmniSharp DLLs etc. are being signed with the same certificate, so I'm not sure why AppLocker is having an issue with this one and not those? We've never published exclusively first-party DLLs because of those dependencies.

**Comment by JustinGrote** [comment]
Maybe it is in fact having a problem with those other DLLs, it just is erroring and exiting *first* on reactive

**Comment by SebCT** [comment]
If i use the React DLL from V2024.0.0, where only ONE CERTIFICATE is in the DLL, it works perfect - with the new one with TWO CERTIFICATES it doesn't work. If i sign it with my own code signer certificate, which is allowlisted in applocker, it works also perfect - and it has only ONE CERTIFCATE after i signed it.

**Comment by andyleejordan** [comment]
I have triple checked this, and it's correct as-is, and I am being required to dual-sign it. Please ask your admins to update their AppLocker rules to accept `System.Reactive.dll` to be signed by `Reactive Extensions for .NET (.NET Foundation)` and `Microsoft 3rd Party Application Component`. If I had to hazard a guess, they wrote a wildcard rule for `System.*`, not expecting a third-party DLL to be prefixed by `System.` such as this one.

**Comment by andyleejordan** [comment]
That lines up with what I heard internally about AppLocker (that while it still exists, it's mostly been deprecated in favor of WDAC due to better security boundaries, and hence its lack of support for dual-signing). Essentially, with the migration to an internal build/sign/release system called OneBranch, I am required to sign all the libraries I ship. When those are signed with a third-party certificate already, I must counter-sign it with that Microsoft 3rdparty Application Component certificate. I don't really have a way around this, the pipeline fails otherwise.

**Comment by SebCT** [comment]
Thanks for the confirmation concerning depreciation of AppLocker, very useful information 🙏🏻
